"""AC-4 substream syntax transcription (the Python reference for src/ac4dec).

Written from ETSI TS 103 190-1 V1.4.1 (Part 1) and ETSI TS 103 190-2 V1.3.1
(Part 2) alone. Part 2 clause 6 amends Part 1 clause 4 (Part 2 tables 48/49);
bitstream_version 2 is what every stream in scope uses. Every syntax element
read from a substream is recorded as (bit_offset, width, value, name) per the
trace contract (docs/verification.md); the TOC is parsed but not recorded.

In scope: ac4_presentation_substream() (Part 2 6.2.2.3), ac4_substream()
(Part 2 6.2.2.2) with audio_data_chan() and the Part 1 channel elements
(single, pair, 3_0, 5_X, 7_X) in every codec mode, and
emdf_payloads_substream() (Part 1 4.2.4.4). Refused (records read before the
refusal are kept): object, A-JOC, OAMD and HSF extension substreams,
immersive_channel_element(), 22_2_channel_element(), the speech spectral
frontend, 96/192 kHz substreams.

Invariants checked (a failure is reported, the substream stops): audio_data
ends inside audio_size (only fill and byte_align left), the tools metadata of
metadata() uses exactly tools_metadata_size bits, drc_frame() in the
presentation substream uses exactly drc_metadata_size bits, and every
substream (after its final byte_align) ends exactly at its substream_size.

Usage:
  python ac4_syntax.py digest <file.ac4> > out.tsv
  python ac4_syntax.py trace <file.ac4> [first_frame last_frame] > out.tsv
Options (before the command): --literal-ims  do not apply the empirical
presentation_version 2 stereo rule (see src/ac4dec/ERRATA.md).
Diagnostics (refusals, invariant failures) go to stderr; the exit status is
1 when any invariant failed.

API: digest_lines(data, stream_name) -> list of the digest file's lines;
walk_stream(data) yields (frame, substream, kind, records).

Standard library only. The TOC comes from ac4_parse.py (same directory), the
tables from ac4_tables.py (generated by
tools/generators/gen_ac4_reference_tables.py).
"""

import math
import struct
import sys
import zlib
from pathlib import Path

import ac4_parse
import ac4_tables as T

# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class Refused(Exception):
    """Out-of-scope syntax: the substream stops here, records so far are kept."""


class SyntaxFail(Exception):
    """An invariant does not hold, or a value the syntax cannot use."""


# ---------------------------------------------------------------------------
# Bit reader with records
# ---------------------------------------------------------------------------

_U64 = struct.Struct('>Q').unpack_from
_PACK = struct.Struct('<IHQ').pack
_MASK64 = (1 << 64) - 1


class Reader:
    __slots__ = ('buf', 'end', 'pos', 'recs')

    def __init__(self, data, recs=None):
        self.buf = bytes(data) + b'\0' * 16
        self.pos = 0
        self.end = len(data) * 8
        self.recs = recs

    # -- raw access --------------------------------------------------------
    def peek(self, n):
        """Next n (<= 57) bits without consuming; zero bits past the end."""
        pos = self.pos
        return (_U64(self.buf, pos >> 3)[0] >> (64 - (pos & 7) - n)) & ((1 << n) - 1)

    def _get(self, n):
        pos = self.pos
        npos = pos + n
        if npos > self.end:
            raise SyntaxFail(f'read of {n} bits at bit {pos} runs past the end ({self.end})')
        if n <= 57:
            v = (_U64(self.buf, pos >> 3)[0] >> (64 - (pos & 7) - n)) & ((1 << n) - 1)
        else:
            v = 0
            left = n
            p = pos
            while left:
                k = 57 if left > 57 else left
                v = (v << k) | ((_U64(self.buf, p >> 3)[0] >> (64 - (p & 7) - k)) & ((1 << k) - 1))
                p += k
                left -= k
        self.pos = npos
        return v

    def u(self, n):
        """Unrecorded read (TOC)."""
        if n == 0:
            return 0
        return self._get(n)

    def f(self, n, name):
        """Recorded fixed- or computed-width field."""
        if n == 0:
            return 0
        if n < 0:
            raise SyntaxFail(f'{name}: negative width {n}')
        pos = self.pos
        v = self._get(n)
        self.recs.append((pos, n, v, name))
        return v

    def vb(self, n_bits, name):
        """variable_bits(n_bits) (Part 1 4.2.2) as one record, whose value is
        kept modulo 2^64 as the trace packs it. A record's width is 16 bits, so
        an element wider than 65535 bits is recorded as consecutive 65535-bit
        records, the last shorter, each valued at its own last 64 bits - the
        rule _wide() follows, and the decoder's emit_element() with it."""
        pos = self.pos
        value = 0
        while True:
            value += self._get(n_bits)
            if not self._get(1):
                break
            value <<= n_bits
            value += 1 << n_bits
        width = self.pos - pos
        if width <= 65535:
            self.recs.append((pos, width, value & _MASK64, name))
            return value
        end = self.pos
        at = pos
        while at < end:
            chunk = min(65535, end - at)
            self.pos = at
            self.recs.append((at, chunk, self._get(chunk) & _MASK64, name))
            at += chunk
        self.pos = end
        return value

    def vb_u(self, n_bits):
        value = 0
        while True:
            value += self._get(n_bits)
            if not self._get(1):
                return value
            value <<= n_bits
            value += 1 << n_bits

    def align(self, base=0):
        """byte_align relative to bit position `base` (not recorded)."""
        rem = (self.pos - base) % 8
        if rem:
            npos = self.pos + 8 - rem
            if npos > self.end:
                raise SyntaxFail(f'byte_align at bit {self.pos} runs past the end ({self.end})')
            self.pos = npos

    def record_raw(self, pos, width, value, name):
        self.recs.append((pos, width, value, name))


# ---------------------------------------------------------------------------
# Huffman codebooks (Part 1 Annex A)
# ---------------------------------------------------------------------------


class Codebook:
    __slots__ = (
        'cb_mod',
        'cb_mod2',
        'cb_mod3',
        'cb_off',
        'l1',
        'long',
        'maxlen',
        'name',
        'shift',
        'size',
        'table',
    )

    def __init__(self, name, spec):
        lens, cws = spec['len'], [int(c, 16) if isinstance(c, str) else c for c in spec['cw']]
        self.name = name
        self.size = len(lens)
        self.maxlen = max(lens)
        self.l1 = min(self.maxlen, 10)
        self.shift = self.maxlen - self.l1
        self.table = [None] * (1 << self.l1)
        self.long = {}
        for i, (length, cw) in enumerate(zip(lens, cws, strict=True)):
            if length <= self.l1:
                base = cw << (self.l1 - length)
                for k in range(1 << (self.l1 - length)):
                    if self.table[base + k] is not None:
                        raise ValueError(f'{name}: codebook not prefix-free')
                    self.table[base + k] = (length, i)
            else:
                self.long[(length, cw)] = i
        self.cb_off = spec['cb_off']
        self.cb_mod = spec['cb_mod']
        self.cb_mod2 = spec['cb_mod2']
        self.cb_mod3 = spec['cb_mod3']

    def decode(self, r, name):
        """huff_decode(): record (length, index) and return the index."""
        pos = r.pos
        maxlen = self.maxlen
        bits = (_U64(r.buf, pos >> 3)[0] >> (64 - (pos & 7) - maxlen)) & ((1 << maxlen) - 1)
        e = self.table[bits >> self.shift]
        if e is not None:
            length, idx = e
        else:
            for length in range(self.l1 + 1, maxlen + 1):
                idx = self.long.get((length, bits >> (maxlen - length)))
                if idx is not None:
                    break
            else:
                raise SyntaxFail(f'{self.name}: no codeword at bit {pos}')
        npos = pos + length
        if npos > r.end:
            raise SyntaxFail(f'{self.name} codeword at bit {pos} runs past the end ({r.end})')
        r.pos = npos
        r.recs.append((pos, length, idx, name))
        return idx


CB = {name: Codebook(name, spec) for name, spec in T.HUFFMAN_CODEBOOKS.items()}
ASF_CB = [None] + [CB[f'ASF_HCB_{i}'] for i in range(1, 12)]
CB_SCALEFAC = CB['ASF_HCB_SCALEFAC']
CB_SNF = CB['ASF_HCB_SNF']

# ---------------------------------------------------------------------------
# Channel modes (Part 1 Table 88, Part 2 Table 56)
# ---------------------------------------------------------------------------

# Channels per ch_mode for superset() (Part 2 6.3.3.1.27): Table 56 plus the
# 7.X.4 / 9.X.4 / 22.2 channel sets of Part 2 table 69.
_CH_SETS = {
    0: {'C'}, 1: {'L', 'R'}, 2: {'L', 'R', 'C'}, 3: {'L', 'R', 'C', 'Ls', 'Rs'},
    5: {'L', 'R', 'C', 'Ls', 'Rs', 'Lb', 'Rb'},
    7: {'L', 'R', 'C', 'Lw', 'Rw', 'Ls', 'Rs'},
    9: {'L', 'R', 'C', 'Ls', 'Rs', 'Tfl', 'Tfr'},
    11: {'L', 'R', 'C', 'Ls', 'Rs', 'Lb', 'Rb', 'Tfl', 'Tfr', 'Tbl', 'Tbr'},
    13: {'L', 'R', 'C', 'Lscr', 'Rscr', 'Ls', 'Rs', 'Lb', 'Rb', 'Tfl', 'Tfr', 'Tbl', 'Tbr'},
    15: {'L', 'R', 'C', 'LFE', 'LFE2', 'Lw', 'Rw', 'Ls', 'Rs', 'Lb', 'Rb', 'Bfl', 'Bfr', 'Bfc',
         'Cb', 'Tfl', 'Tfr', 'Tbl', 'Tbr', 'Tsl', 'Tsr', 'Tfc', 'Tbc', 'Tc'},
}
for _m in (4, 6, 8, 10, 12, 14):
    _CH_SETS[_m] = _CH_SETS[_m - 1] | {'LFE'}
_CORE_SETS = {3: {'L', 'R', 'C', 'Ls', 'Rs'}, 4: {'L', 'R', 'C', 'Ls', 'Rs', 'LFE'},
              5: {'L', 'R', 'C', 'Ls', 'Rs', 'Tl', 'Tr'},
              6: {'L', 'R', 'C', 'Ls', 'Rs', 'Tl', 'Tr', 'LFE'}}


def superset(a, b, sets=_CH_SETS):
    if a == -1:
        return b
    if b == -1:
        return a
    if {a, b} == {0, 1}:
        return 1
    need = sets[a] | sets[b]
    for m in sorted(sets):
        if need <= sets[m]:
            return m
    # Six pairs have no mode holding both - 5/2/0(.1) brings Lw/Rw and 9.X.4
    # brings Lscr/Rscr, 22.2 has the first pair and not the second - and
    # 6.3.3.1.27 gives no result for them. -1, the way the decoder reads it:
    # the presentation has no single channel mode, and the presentation
    # substream reads the fields that answer to that. Returning the larger mode
    # would name a layout the presentation does not have, dropping the LFE of
    # 5/2/0.1 against 9.0.4 (src/ac4dec/ERRATA.md, "The presentation
    # substream").
    return -1


def contains_lfe(m):
    return m in (4, 6, 8, 10, 12, 14, 15)


def contains_c(m):
    return m == 0 or 2 <= m <= 15


def contains_lr(m):
    return 1 <= m <= 15


def contains_lsrs(m):
    return 3 <= m <= 15


def contains_lbrb(m):
    return m in (5, 6) or 11 <= m <= 15


def contains_lwrw(m):
    return m in (7, 8, 15)


def contains_tfltfr(m):
    return m in (9, 10)


# ---------------------------------------------------------------------------
# Audio spectral frontend (Part 1 4.2.7, 4.2.8, 4.3.6)
# ---------------------------------------------------------------------------


class SfInfo:
    """asf_transform_info() + asf_psy_info() and the helper elements of
    Part 1 4.3.6.2.6 (Pseudocode 3/4) and get_max_sfb / get_transf_length."""

    __slots__ = (
        'b_dual_maxsfb',
        'b_side_limited',
        'flb',
        'group_idx',
        'group_len',
        'group_tl',
        'long_frame',
        'master_override',
        'max_sfb',
        'max_sfb_side',
        'num_win_in_group',
        'num_window_groups',
        'num_windows',
        'tl',
        'tl_len',
        'window_to_group',
    )

    def get_max_sfb(self, g, side=False):
        if self.master_override is not None:
            return self.master_override[g]
        idx = self.group_idx[g]
        if self.b_side_limited or (self.b_dual_maxsfb and side):
            return self.max_sfb_side[idx]
        return self.max_sfb[idx]

    def largest_len(self):
        return max(self.tl_len)


def _full_frame_index(flb):
    """The transform index whose transform covers the whole frame (Table 103):
    4 at 1536 samples and above, 3 for 1024, 960 and 768, 2 for 512 and 384.
    It decides the widths Table 39 takes from the index, not only the length."""
    if flb >= 1536:
        return 4
    return 2 if flb in (512, 384) else 3


def sf_info_lfe(r, ctx):
    """Part 1 Table 35."""
    flb = ctx.flb
    s = SfInfo()
    s.flb = flb
    s.long_frame = 1
    # Table 35 gives the LFE no transf_length: its transform covers the frame,
    # so the index is the whole-frame one. This used to be 4 whatever the frame
    # length, which reads sect_len_incr 5 bits wide at 512 and 384 samples where
    # Table 39 takes 3 (src/ac4dec/ERRATA.md, "sf_info_lfe() below 1536 samples"
    # and "n_sect_bits below 1536 samples").
    s.tl = (_full_frame_index(flb),) * 2
    s.tl_len = (flb, flb)
    bits = T.N_MSFB_BITS_48[flb][2]
    s.max_sfb = [r.f(bits, 'max_sfb[0]'), 0]
    s.max_sfb_side = [0, 0]
    s.b_dual_maxsfb = 0
    s.b_side_limited = 0
    s.num_windows = 1
    s.num_window_groups = 1
    s.window_to_group = [0]
    s.num_win_in_group = [1]
    s.group_tl = [s.tl[0]]
    s.group_len = [flb]
    s.group_idx = [0]
    s.master_override = None
    if s.max_sfb[0] > T.NUM_SFB_48[flb]:
        raise SyntaxFail(f'LFE max_sfb {s.max_sfb[0]} > num_sfb {T.NUM_SFB_48[flb]}')
    return s


def sf_info(r, ctx, b_dual_maxsfb=0, b_side_limited=0):
    """Part 1 Table 34 for spec_frontend == ASF (Tables 37, 38)."""
    flb = ctx.flb
    s = SfInfo()
    s.flb = flb
    s.b_dual_maxsfb = b_dual_maxsfb
    s.b_side_limited = b_side_limited
    s.master_override = None
    # asf_transform_info()
    if flb >= 1536:
        s.long_frame = r.f(1, 'b_long_frame')
        if s.long_frame == 0:
            t0 = r.f(2, 'transf_length[0]')
            t1 = r.f(2, 'transf_length[1]')
            s.tl = (t0, t1)
            row = T.TRANSF_LENGTH_LONG_BASE[flb]
            s.tl_len = (row[t0], row[t1])
            n_grp_bits = T.N_GRP_BITS_LONG_BASE[(t0, t1)]
        else:
            s.tl = (4, 4)
            s.tl_len = (flb, flb)
            n_grp_bits = 0
    else:
        s.long_frame = 0
        t = r.f(2, 'transf_length')
        length = T.TRANSF_LENGTH_SHORT_BASE[flb][t]
        if length is None:
            raise SyntaxFail(f'transf_length {t} not allowed for frame_len_base {flb}')
        s.tl = (t, t)
        s.tl_len = (length, length)
        n_grp_bits = T.N_GRP_BITS_SHORT_BASE[flb][t]
    # asf_psy_info()
    b_diff = 1 if (flb >= 1536 and s.long_frame == 0 and s.tl[0] != s.tl[1]) else 0
    s.max_sfb = [0, 0]
    s.max_sfb_side = [0, 0]
    for i in ((0, 1) if b_diff else (0,)):
        msfb_bits, side_bits, _ = T.N_MSFB_BITS_48[s.tl_len[i]]
        if b_side_limited:
            s.max_sfb_side[i] = r.f(side_bits, f'max_sfb_side[{i}]')
        else:
            s.max_sfb[i] = r.f(msfb_bits, f'max_sfb[{i}]')
            if b_dual_maxsfb:
                s.max_sfb_side[i] = r.f(msfb_bits, f'max_sfb_side[{i}]')
        n = T.NUM_SFB_48[s.tl_len[i]]
        if s.max_sfb[i] > n or s.max_sfb_side[i] > n:
            raise SyntaxFail(f'max_sfb {s.max_sfb[i]}/{s.max_sfb_side[i]} > num_sfb {n}')
    grouping = [r.f(1, 'scale_factor_grouping_bit') for _ in range(n_grp_bits)] + [0]
    # Pseudocode 3
    num_windows = 1
    num_window_groups = 1
    if s.long_frame == 0:
        num_windows = n_grp_bits + 1
        if b_diff:
            nw0 = 1 << (3 - s.tl[0])
            for i in range(n_grp_bits, nw0 - 1, -1):
                grouping[i] = grouping[i - 1]
            grouping[nw0 - 1] = 0
            num_windows += 1
        window_to_group = [0] * num_windows
        for i in range(num_windows - 1):
            if grouping[i] == 0:
                num_window_groups += 1
            window_to_group[i + 1] = num_window_groups - 1
    else:
        window_to_group = [0]
    s.num_windows = num_windows
    s.num_window_groups = num_window_groups
    s.window_to_group = window_to_group
    s.num_win_in_group = [window_to_group.count(g) for g in range(num_window_groups)]
    # get_transf_length(g) (Pseudocode 2) and the max_sfb index of get_max_sfb(g) (Pseudocode 5)
    s.group_tl = []
    s.group_len = []
    s.group_idx = []
    for g in range(num_window_groups):
        if flb >= 1536:
            if s.long_frame == 0:
                nw0 = 1 << (3 - s.tl[0])
                first_second = window_to_group[nw0]
                k = 0 if g < first_second else 1
                s.group_tl.append(s.tl[k])
                s.group_len.append(s.tl_len[k])
                s.group_idx.append(1 if (b_diff and g >= first_second) else 0)
            else:
                s.group_tl.append(4)
                s.group_len.append(flb)
                s.group_idx.append(0)
        else:
            s.group_tl.append(s.tl[0])
            s.group_len.append(s.tl_len[0])
            s.group_idx.append(0)
    return s


def _group_offsets(sfi, g, max_sfb, group_offset):
    """sect_sfb_offset[g][0..max_sfb] (Pseudocode 4, extended to sfb == max_sfb)."""
    off = T.SFB_OFFSET_48[sfi.group_len[g]]
    nw = sfi.num_win_in_group[g]
    return [group_offset + off[sfb] * nw for sfb in range(max_sfb + 1)]


def sf_data(r, ctx, sfi, side=False):
    """Part 1 Table 36 for ASF: section, spectral, scale factor, SNF data."""
    ngroups = sfi.num_window_groups
    max_sfbs = [sfi.get_max_sfb(g, side) for g in range(ngroups)]
    offsets = []
    group_offset = 0
    for g in range(ngroups):
        bounds = _group_offsets(sfi, g, max_sfbs[g], group_offset)
        offsets.append(bounds)
        group_offset = bounds[-1]
    # asf_section_data() (Table 39)
    sections = []      # per group: list of (cb, sect_start, sect_end)
    sec_lsf = []
    sfb_cbs = []
    for g in range(ngroups):
        tlg = sfi.group_tl[g]
        if tlg <= 2:
            esc, nbits = 7, 3
        else:
            esc, nbits = 31, 5
        n48 = T.NUM_SFB_48[sfi.group_len[g]]
        max_sfb = max_sfbs[g]
        secs = []
        sfb_cb = [0] * max_sfb
        num_sec_lsf = 0
        k = 0
        while k < max_sfb:
            cb = r.f(4, 'sect_cb')
            sect_len = 1
            while True:
                incr = r.f(nbits, 'sect_len_incr')
                if incr != esc:
                    break
                sect_len += esc
            sect_len += incr
            start, end = k, k + sect_len
            if cb > 11:
                raise SyntaxFail(f'sect_cb {cb} is not a Huffman codebook')
            if end > max_sfb:
                raise SyntaxFail(f'section ends at sfb {end} beyond max_sfb {max_sfb}')
            if start < n48 <= end:
                num_sec_lsf = len(secs) + 1
                if end > n48:
                    secs.append((cb, start, n48))
                    secs.append((cb, n48, end))
                else:
                    secs.append((cb, start, end))
            else:
                secs.append((cb, start, end))
            for sfb in range(k, k + sect_len):
                sfb_cb[sfb] = cb
            k += sect_len
        if num_sec_lsf == 0:
            num_sec_lsf = len(secs)
        sections.append(secs)
        sec_lsf.append(num_sec_lsf)
        sfb_cbs.append(sfb_cb)
    # asf_spectral_data() (Table 40)
    max_quant = []
    for g in range(ngroups):
        bounds = offsets[g]
        mq = [0] * max_sfbs[g]
        for i in range(sec_lsf[g]):
            cb, sstart, send = sections[g][i]
            if cb == 0 or cb > 11:
                if cb > 11:
                    raise SyntaxFail(f'sect_cb {cb} is not a Huffman codebook')
                continue
            hcb = ASF_CB[cb]
            dim = T.CB_DIM[cb]
            unsigned = T.UNSIGNED_CB[cb]
            off = hcb.cb_off
            k = bounds[sstart]
            kend = bounds[send]
            s = sstart
            decode = hcb.decode
            while k < kend:
                while k >= bounds[s + 1]:
                    s += 1
                idx = decode(r, 'asf_qspec_hcw')
                if dim == 4:
                    m3, m2, m1 = hcb.cb_mod3, hcb.cb_mod2, hcb.cb_mod
                    q1 = idx // m3 - off
                    idx -= (q1 + off) * m3
                    q2 = idx // m2 - off
                    idx -= (q2 + off) * m2
                    q3 = idx // m1 - off
                    idx -= (q3 + off) * m1
                    q4 = idx - off
                    if unsigned:
                        nz = (q1 != 0) + (q2 != 0) + (q3 != 0) + (q4 != 0)
                        if nz:
                            r.f(nz, 'quad_sign_bits')
                    if q1 or q2 or q3 or q4:
                        mq[s] = 1
                    k += 4
                else:
                    m1 = hcb.cb_mod
                    q1 = idx // m1 - off
                    q2 = idx - (q1 + off) * m1 - off
                    if unsigned:
                        nz = (q1 != 0) + (q2 != 0)
                        if nz:
                            r.f(nz, 'pair_sign_bits')
                    if cb == 11:
                        if q1 == 16:
                            ext_code(r)
                        if q2 == 16:
                            ext_code(r)
                    if q1 or q2:
                        mq[s] = 1
                    k += 2
            if k != kend:
                raise SyntaxFail('spectral codewords overrun the section end')
        max_quant.append(mq)
    # asf_scalefac_data() (Table 41)
    r.f(8, 'reference_scale_factor')
    first = 0
    for g in range(ngroups):
        lim = min(max_sfbs[g], T.NUM_SFB_48[sfi.group_len[g]])
        cbs = sfb_cbs[g]
        mq = max_quant[g]
        for sfb in range(lim):
            if cbs[sfb] != 0 and mq[sfb]:
                if first:
                    CB_SCALEFAC.decode(r, 'asf_sf_hcw')
                else:
                    first = 1
    # asf_snf_data() (Table 42)
    if r.f(1, 'b_snf_data_exists'):
        for g in range(ngroups):
            lim = min(max_sfbs[g], T.NUM_SFB_48[sfi.group_len[g]])
            cbs = sfb_cbs[g]
            mq = max_quant[g]
            for sfb in range(lim):
                if cbs[sfb] == 0 or not mq[sfb]:
                    CB_SNF.decode(r, 'asf_snf_hcw')
    ctx.tracks.append(sfi)


def ext_code(r):
    """Pseudocode 20: one record for the whole escape, value 2^(N_ext+4) + ext_val.
    Table 40 gives ext_code 5 to 21 bits (2 * N_ext + 5), so a ninth leading
    one fails the substream, with nothing recorded (see src/ac4dec/ERRATA.md)."""
    pos = r.pos
    n_ext = 0
    while r._get(1):
        n_ext += 1
        if n_ext > 8:
            raise SyntaxFail('ext_code is longer than 21 bits')
    val = r._get(n_ext + 4)
    r.recs.append((pos, r.pos - pos, (1 << (n_ext + 4)) + val, 'ext_code'))


# ---------------------------------------------------------------------------
# Stereo audio processing (Part 1 4.2.10), companding (4.2.11)
# ---------------------------------------------------------------------------


def chparam_info(r, sfi):
    sap_mode = r.f(2, 'sap_mode')
    if sap_mode == 1:
        for g in range(sfi.num_window_groups):
            for _ in range(sfi.get_max_sfb(g)):
                r.f(1, 'ms_used')
    elif sap_mode == 3:
        # sap_data() (Table 48)
        ngroups = sfi.num_window_groups
        used = []
        if r.f(1, 'sap_coeff_all') == 0:
            for g in range(ngroups):
                m = sfi.get_max_sfb(g)
                u = [0] * m
                for sfb in range(0, m, 2):
                    u[sfb] = r.f(1, 'sap_coeff_used')
                    if sfb + 1 < m:
                        u[sfb + 1] = u[sfb]
                used.append(u)
        else:
            used = [[1] * sfi.get_max_sfb(g) for g in range(ngroups)]
        if ngroups != 1:
            r.f(1, 'delta_code_time')
        for g in range(ngroups):
            m = sfi.get_max_sfb(g)
            for sfb in range(0, m, 2):
                if used[g][sfb]:
                    CB_SCALEFAC.decode(r, 'sap_hcw')


def companding_control(r, num_chan):
    sync = r.f(1, 'sync_flag') if num_chan > 1 else 0
    need_avg = 0
    for _ in range(1 if sync else num_chan):
        if not r.f(1, 'b_compand_on'):
            need_avg = 1
    if need_avg:
        r.f(1, 'b_compand_avg')


# ---------------------------------------------------------------------------
# A-SPX (Part 1 4.2.12, 5.7.6.3)
# ---------------------------------------------------------------------------

FIXFIX, FIXVAR, VARFIX, VARVAR = 0, 1, 2, 3
_ASPX_CFG = [('aspx_quant_mode_env', 1), ('aspx_start_freq', 3), ('aspx_stop_freq', 2),
             ('aspx_master_freq_scale', 1), ('aspx_interpolation', 1), ('aspx_preflat', 1),
             ('aspx_limiter', 1), ('aspx_noise_sbg', 2), ('aspx_num_env_bits_fixfix', 1),
             ('aspx_freq_res_mode', 2)]


def aspx_config(r, ctx):
    ctx.state['aspx_config'] = {name: r.f(n, name) for name, n in _ASPX_CFG}


def _aspx_bands(cfg, xover):
    """Pseudocode 67-70: num_sbg_sig_highres, num_sbg_sig_lowres, num_sbg_noise."""
    start, stop = cfg['aspx_start_freq'], cfg['aspx_stop_freq']
    if cfg['aspx_master_freq_scale'] == 1:
        n_master = 22 - 2 * start - 2 * stop
        tmpl = T.SBG_TEMPLATE_HIGHRES
    else:
        n_master = 20 - 2 * start - 2 * stop
        tmpl = T.SBG_TEMPLATE_LOWRES
    if n_master < 1:
        raise SyntaxFail(f'num_sbg_master {n_master}')
    master = tmpl[2 * start:2 * start + n_master + 1]
    sbz = master[n_master]
    n_high = n_master - xover
    if n_high < 1:
        raise SyntaxFail(f'aspx_xover_subband_offset {xover} >= num_sbg_master {n_master}')
    sbx = master[xover]
    n_low = n_high - n_high // 2
    n_noise = max(1, math.floor(cfg['aspx_noise_sbg'] * math.log2(sbz / sbx) + 0.5))
    # 5.7.6.3.1.3 caps num_sbg_noise at 5. Five of the 1,808 legal A-SPX
    # settings give more, all with aspx_noise_sbg 3 on the low-resolution
    # master scale, and reading on there would take a noise envelope per band
    # the syntax does not have (src/ac4dec/ERRATA.md, "num_sbg_noise above 5").
    if n_noise > 5:
        raise SyntaxFail(f'num_sbg_noise {n_noise} exceeds 5 (5.7.6.3.1.3)')
    return n_high, n_low, n_noise


class AspxChannel:
    __slots__ = (
        'atsg_freqres',
        'freq_res',
        'int_class',
        'noise_dir',
        'num_env',
        'num_noise',
        'qmode',
        'rel_left',
        'rel_right',
        'sig_dir',
        'tsg_ptr',
        'var_bord_left',
        'var_bord_right',
    )


def aspx_framing(r, ctx, ch, nts, cfg, b_iframe, prev_stop):
    c = AspxChannel()
    rel_bits = 2 if nts > 8 else 1
    pos = r.pos
    b = r._get(1)
    if b == 0:
        cls, width, code = FIXFIX, 1, 0
    else:
        b = r._get(1)
        if b == 0:
            cls, width, code = FIXVAR, 2, 0b10
        else:
            b = r._get(1)
            cls, width, code = (VARFIX, 3, 0b110) if b == 0 else (VARVAR, 3, 0b111)
    r.record_raw(pos, width, code, 'aspx_int_class')
    c.int_class = cls
    c.rel_left = []
    c.rel_right = []
    c.var_bord_left = None
    c.var_bord_right = None
    c.freq_res = []
    c.tsg_ptr = 0
    if cls == FIXFIX:
        envbits = cfg['aspx_num_env_bits_fixfix'] + 1
        c.num_env = 1 << r.f(envbits, 'tmp_num_env')
        if c.num_env > 4:
            raise SyntaxFail(f'aspx_num_env {c.num_env} exceeds Table 128 for class {cls}')
        if cfg['aspx_freq_res_mode'] == 0:
            c.freq_res = [r.f(1, 'aspx_freq_res')]
    else:
        if cls == FIXVAR:
            c.var_bord_right = r.f(2, 'aspx_var_bord_right')
            n = r.f(rel_bits, 'aspx_num_rel_right')
            c.rel_right = [2 * r.f(rel_bits, 'aspx_rel_bord_right') + 2 for _ in range(n)]
        else:
            if b_iframe:
                c.var_bord_left = r.f(2, 'aspx_var_bord_left')
            n = r.f(rel_bits, 'aspx_num_rel_left')
            c.rel_left = [2 * r.f(rel_bits, 'aspx_rel_bord_left') + 2 for _ in range(n)]
            if cls == VARVAR:
                c.var_bord_right = r.f(2, 'aspx_var_bord_right')
                n = r.f(rel_bits, 'aspx_num_rel_right')
                c.rel_right = [2 * r.f(rel_bits, 'aspx_rel_bord_right') + 2 for _ in range(n)]
        c.num_env = len(c.rel_left) + len(c.rel_right) + 1
        if c.num_env > 5:
            raise SyntaxFail(f'aspx_num_env {c.num_env} exceeds Table 128 for class {cls}')
        ptr_bits = (c.num_env + 2 - 1).bit_length()  # ceil(log2(num_env + 2))
        c.tsg_ptr = r.f(ptr_bits, 'aspx_tsg_ptr') - 1
        if cfg['aspx_freq_res_mode'] == 0:
            c.freq_res = [r.f(1, 'aspx_freq_res') for _ in range(c.num_env)]
    c.num_noise = 2 if c.num_env > 1 else 1
    # Pseudocode 76/77: atsg_sig borders and atsg_freqres (the aspx_ec_data count needs it)
    if cls == FIXFIX:
        if c.num_env not in T.TAB_BORDER[nts]:
            raise SyntaxFail(f'FIXFIX with {c.num_env} envelopes')
        atsg = list(T.TAB_BORDER[nts][c.num_env])
    else:
        atsg = [0] * (c.num_env + 1)
        if cls == FIXVAR:
            atsg[0] = 0
            atsg[c.num_env] = c.var_bord_right + nts
        else:
            atsg[0] = c.var_bord_left if b_iframe else prev_stop - nts
            atsg[c.num_env] = nts if cls == VARFIX else c.var_bord_right + nts
        for t, v in enumerate(c.rel_left):
            atsg[t + 1] = atsg[t] + v
        for t, v in enumerate(c.rel_right):
            atsg[c.num_env - t - 1] = atsg[c.num_env - t] - v
    mode = cfg['aspx_freq_res_mode']

    def freq_res(a, ptr):
        if mode == 0:
            return c.freq_res[a]
        if mode == 1:
            return 0
        if mode == 2:
            high = (a < ptr and nts > 8) or (atsg[a + 1] - atsg[a]) > (nts / 6.0 + 3.25)
            return 1 if high else 0
        return 1

    if cls == FIXFIX:
        fr0 = freq_res(0, 0)
        c.atsg_freqres = [fr0] * c.num_env
    else:
        c.atsg_freqres = [freq_res(a, c.tsg_ptr) for a in range(c.num_env)]
    return c, atsg[c.num_env]


def aspx_delta_dir(r, c):
    c.sig_dir = [r.f(1, 'aspx_sig_delta_dir') for _ in range(c.num_env)]
    c.noise_dir = [r.f(1, 'aspx_noise_delta_dir') for _ in range(c.num_noise)]


def aspx_ec_data(r, data_type, c, qmode, balance, bands):
    n_high, n_low, n_noise = bands
    stereo = 'BALANCE' if balance else 'LEVEL'
    if data_type == 'SIGNAL':
        q = '30' if qmode else '15'
        f0 = CB[f'ASPX_HCB_ENV_{stereo}_{q}_F0']
        df = CB[f'ASPX_HCB_ENV_{stereo}_{q}_DF']
        dt = CB[f'ASPX_HCB_ENV_{stereo}_{q}_DT']
        n_env = c.num_env
        dirs = c.sig_dir
    else:
        f0 = CB[f'ASPX_HCB_NOISE_{stereo}_F0']
        df = CB[f'ASPX_HCB_NOISE_{stereo}_DF']
        dt = CB[f'ASPX_HCB_NOISE_{stereo}_DT']
        n_env = c.num_noise
        dirs = c.noise_dir
    for env in range(n_env):
        if data_type == 'SIGNAL':
            num_sbg = n_high if c.atsg_freqres[env] else n_low
        else:
            num_sbg = n_noise
        if dirs[env] == 0:
            f0.decode(r, 'aspx_hcw')
            for _ in range(1, num_sbg):
                df.decode(r, 'aspx_hcw')
        else:
            for _ in range(num_sbg):
                dt.decode(r, 'aspx_hcw')


def _aspx_prepare(ctx, occ, b_iframe, r):
    cfg = ctx.state.get('aspx_config')
    if cfg is None:
        raise SyntaxFail('A-SPX data before any aspx_config')
    xkey = ('aspx_xover', occ)
    if b_iframe:
        ctx.state[xkey] = r.f(3, 'aspx_xover_subband_offset')
    if xkey not in ctx.state:
        raise SyntaxFail('A-SPX data before any aspx_xover_subband_offset')
    bands = _aspx_bands(cfg, ctx.state[xkey])
    flen = ctx.flb
    nts = (flen // 64) // T.NUM_TS_IN_ATS[flen]
    return cfg, bands, nts


def aspx_data_1ch(r, ctx):
    occ = ctx.next_aspx_occurrence()
    b_iframe = ctx.b_iframe
    cfg, bands, nts = _aspx_prepare(ctx, occ, b_iframe, r)
    skey = ('aspx_prev_stop', occ, 0)
    c, stop = aspx_framing(r, ctx, 0, nts, cfg, b_iframe, ctx.state.get(skey, nts))
    ctx.state[skey] = stop
    c.qmode = cfg['aspx_quant_mode_env']
    if c.int_class == FIXFIX and c.num_env == 1:
        c.qmode = 0
    aspx_delta_dir(r, c)
    # aspx_hfgen_iwc_1ch() (Table 55)
    n_high, _, n_noise = bands
    for _ in range(n_noise):
        r.f(2, 'aspx_tna_mode')
    if r.f(1, 'aspx_ah_present'):
        for _ in range(n_high):
            r.f(1, 'aspx_add_harmonic')
    if r.f(1, 'aspx_fic_present'):
        for _ in range(n_high):
            r.f(1, 'aspx_fic_used_in_sfb')
    if r.f(1, 'aspx_tic_present'):
        for _ in range(nts):
            r.f(1, 'aspx_tic_used_in_slot')
    aspx_ec_data(r, 'SIGNAL', c, c.qmode, 0, bands)
    aspx_ec_data(r, 'NOISE', c, 0, 0, bands)


def aspx_data_2ch(r, ctx):
    occ = ctx.next_aspx_occurrence()
    b_iframe = ctx.b_iframe
    cfg, bands, nts = _aspx_prepare(ctx, occ, b_iframe, r)
    k0 = ('aspx_prev_stop', occ, 0)
    k1 = ('aspx_prev_stop', occ, 1)
    c0, stop0 = aspx_framing(r, ctx, 0, nts, cfg, b_iframe, ctx.state.get(k0, nts))
    ctx.state[k0] = stop0
    c0.qmode = cfg['aspx_quant_mode_env']
    if c0.int_class == FIXFIX and c0.num_env == 1:
        c0.qmode = 0
    q1 = c0.qmode
    balance = r.f(1, 'aspx_balance')
    if balance == 0:
        c1, stop1 = aspx_framing(r, ctx, 1, nts, cfg, b_iframe, ctx.state.get(k1, nts))
        ctx.state[k1] = stop1
        c1.qmode = cfg['aspx_quant_mode_env']
        if c1.int_class == FIXFIX and c1.num_env == 1:
            c1.qmode = 0
    else:
        # aspx_framing(1) is not read: channel 1 takes channel 0's framing
        # (src/ac4dec/ERRATA.md)
        c1 = AspxChannel()
        for slot in ('int_class', 'num_env', 'num_noise', 'freq_res', 'var_bord_left',
                     'var_bord_right', 'rel_left', 'rel_right', 'tsg_ptr', 'atsg_freqres'):
            setattr(c1, slot, getattr(c0, slot))
        c1.qmode = q1
        ctx.state[k1] = stop0
    aspx_delta_dir(r, c0)
    aspx_delta_dir(r, c1)
    # aspx_hfgen_iwc_2ch(aspx_balance) (Table 56)
    n_high, _, n_noise = bands
    for _ in range(n_noise):
        r.f(2, 'aspx_tna_mode')
    if balance == 0:
        for _ in range(n_noise):
            r.f(2, 'aspx_tna_mode')
    if r.f(1, 'aspx_ah_left'):
        for _ in range(n_high):
            r.f(1, 'aspx_add_harmonic')
    if r.f(1, 'aspx_ah_right'):
        for _ in range(n_high):
            r.f(1, 'aspx_add_harmonic')
    if r.f(1, 'aspx_fic_present'):
        if r.f(1, 'aspx_fic_left'):
            for _ in range(n_high):
                r.f(1, 'aspx_fic_used_in_sfb')
        if r.f(1, 'aspx_fic_right'):
            for _ in range(n_high):
                r.f(1, 'aspx_fic_used_in_sfb')
    if r.f(1, 'aspx_tic_present'):
        copy = r.f(1, 'aspx_tic_copy')
        left = right = 0
        if copy == 0:
            left = r.f(1, 'aspx_tic_left')
            right = r.f(1, 'aspx_tic_right')
        if copy or left:
            for _ in range(nts):
                r.f(1, 'aspx_tic_used_in_slot')
        if right:
            for _ in range(nts):
                r.f(1, 'aspx_tic_used_in_slot')
    aspx_ec_data(r, 'SIGNAL', c0, c0.qmode, 0, bands)
    aspx_ec_data(r, 'SIGNAL', c1, c1.qmode, balance, bands)
    aspx_ec_data(r, 'NOISE', c0, 0, 0, bands)
    aspx_ec_data(r, 'NOISE', c1, 0, balance, bands)


# ---------------------------------------------------------------------------
# A-CPL (Part 1 4.2.13)
# ---------------------------------------------------------------------------


def acpl_config_1ch(r, ctx, partial):
    bid = r.f(2, 'acpl_num_param_bands_id')
    cfg = {'num_bands': T.ACPL_NUM_PARAM_BANDS[bid], 'quant_mode': r.f(1, 'acpl_quant_mode'),
           'param_band': 0}
    if partial:
        qmf_band = r.f(3, 'acpl_qmf_band_minus1') + 1
        cfg['param_band'] = T.SB_TO_PB[cfg['num_bands']][qmf_band]
    ctx.state['acpl_config'] = cfg


def acpl_config_2ch(r, ctx):
    bid = r.f(2, 'acpl_num_param_bands_id')
    ctx.state['acpl_config'] = {'num_bands': T.ACPL_NUM_PARAM_BANDS[bid],
                                'quant_mode_0': r.f(1, 'acpl_quant_mode_0'),
                                'quant_mode_1': r.f(1, 'acpl_quant_mode_1'), 'param_band': 0}


def _acpl_framing(r):
    interp = r.f(1, 'acpl_interpolation_type')
    cod = r.f(1, 'acpl_num_param_sets_cod')
    if interp == 1:
        for _ in range(cod + 1):
            r.f(5, 'acpl_param_timeslot')
    return cod + 1


def _acpl_ec_data(r, data_type, bands, start, quant_mode, n_ps):
    q = 'COARSE' if quant_mode else 'FINE'
    f0 = CB[f'ACPL_HCB_{data_type}_{q}_F0']
    df = CB[f'ACPL_HCB_{data_type}_{q}_DF']
    dt = CB[f'ACPL_HCB_{data_type}_{q}_DT']
    for _ in range(n_ps):
        if r.f(1, 'diff_type') == 0:
            f0.decode(r, 'acpl_hcw')
            for _ in range(start + 1, bands):
                df.decode(r, 'acpl_hcw')
        else:
            for _ in range(start, bands):
                dt.decode(r, 'acpl_hcw')


def acpl_data_1ch(r, ctx):
    cfg = ctx.state.get('acpl_config')
    if cfg is None or 'quant_mode' not in cfg:
        raise SyntaxFail('acpl_data_1ch before any acpl_config_1ch')
    n_ps = _acpl_framing(r)
    _acpl_ec_data(r, 'ALPHA', cfg['num_bands'], cfg['param_band'], cfg['quant_mode'], n_ps)
    _acpl_ec_data(r, 'BETA', cfg['num_bands'], cfg['param_band'], cfg['quant_mode'], n_ps)


def acpl_data_2ch(r, ctx):
    cfg = ctx.state.get('acpl_config')
    if cfg is None or 'quant_mode_0' not in cfg:
        raise SyntaxFail('acpl_data_2ch before any acpl_config_2ch')
    n_ps = _acpl_framing(r)
    nb, st, q0, q1 = cfg['num_bands'], cfg['param_band'], cfg['quant_mode_0'], cfg['quant_mode_1']
    for dtype, q in (('ALPHA', q0), ('ALPHA', q0), ('BETA', q0), ('BETA', q0), ('BETA3', q0),
                     ('GAMMA', q1), ('GAMMA', q1), ('GAMMA', q1), ('GAMMA', q1), ('GAMMA', q1),
                     ('GAMMA', q1)):
        _acpl_ec_data(r, dtype, nb, st, q, n_ps)


# ---------------------------------------------------------------------------
# Channel elements (Part 1 4.2.5, 4.2.6)
# ---------------------------------------------------------------------------


class AudioCtx:
    def __init__(self, flb, b_iframe, state, ch_mode, add_ch_base=0):
        self.flb = flb
        self.b_iframe = b_iframe
        self.state = state
        self.ch_mode = ch_mode
        self.add_ch_base = add_ch_base
        self.aspx_occ = 0
        self.last_sfi = None
        self.element_sfis = []
        # The sf_info of every sf_data() read so far in the element, in order:
        # track k of the channel data is tracks[mark + k].
        self.tracks = []

    def next_aspx_occurrence(self):
        occ = self.aspx_occ
        self.aspx_occ += 1
        return occ


def _spec_frontend(r, name):
    v = r.f(1, name)
    if v == 1:
        raise Refused(f'{name} selects the speech spectral frontend (SSF)')
    return v


def _configure(ctx, element, mode, needs_config):
    """The configuration an element's I-frame sends (aspx_config(),
    acpl_config_*()) belongs to the element and codec mode it was sent for.
    An I-frame starts it afresh, forgetting the A-SPX offsets and borders when
    the element or its codec mode changed; a later frame in another codec mode
    that needs configuration fails."""
    st = ctx.state
    if ctx.b_iframe:
        if st.get('configured') != (element, mode):
            for key in [k for k in st if isinstance(k, tuple) and k[0] in ('aspx_xover',
                                                                         'aspx_prev_stop')]:
                st.pop(key)
        st['configured'] = (element, mode)
        st.pop('aspx_config', None)
        st.pop('acpl_config', None)
    elif needs_config and st.get('configured') != (element, mode):
        raise SyntaxFail('this codec mode needs configuration that no I-frame has sent')


def _sfi(r, ctx, dual=0, side_limited=0):
    s = sf_info(r, ctx, dual, side_limited)
    ctx.last_sfi = s
    ctx.element_sfis.append(s)
    return s


def mono_data(r, ctx, b_lfe):
    if b_lfe:
        s = sf_info_lfe(r, ctx)
    else:
        _spec_frontend(r, 'spec_frontend')
        s = _sfi(r, ctx)
    sf_data(r, ctx, s)


def stereo_data(r, ctx):
    if r.f(1, 'b_enable_mdct_stereo_proc'):
        s = _sfi(r, ctx)
        chparam_info(r, s)
        sf_data(r, ctx, s)
        sf_data(r, ctx, s)
    else:
        _spec_frontend(r, 'spec_frontend_l')
        sl = _sfi(r, ctx)
        _spec_frontend(r, 'spec_frontend_r')
        sr = _sfi(r, ctx)
        sf_data(r, ctx, sl)
        sf_data(r, ctx, sr)


def two_channel_data(r, ctx):
    if r.f(1, 'b_enable_mdct_stereo_proc'):
        s = _sfi(r, ctx)
        chparam_info(r, s)
        sf_data(r, ctx, s)
        sf_data(r, ctx, s)
    else:
        s0 = _sfi(r, ctx)
        s1 = _sfi(r, ctx)
        sf_data(r, ctx, s0)
        sf_data(r, ctx, s1)


def three_channel_data(r, ctx):
    s = _sfi(r, ctx)
    r.f(4, 'chel_matsel')
    chparam_info(r, s)
    chparam_info(r, s)
    for _ in range(3):
        sf_data(r, ctx, s)


def four_channel_data(r, ctx):
    s = _sfi(r, ctx)
    for _ in range(4):
        chparam_info(r, s)
    for _ in range(4):
        sf_data(r, ctx, s)


def five_channel_data(r, ctx):
    s = _sfi(r, ctx)
    r.f(4, 'chel_matsel')
    for _ in range(5):
        chparam_info(r, s)
    for _ in range(5):
        sf_data(r, ctx, s)


def _tracks_at(ctx, mark, positions):
    """The sf_info of the channel data's tracks at `positions` (counted from
    the first sf_data() read after `mark`)."""
    out = []
    for p in positions:
        if mark + p >= len(ctx.tracks):
            raise SyntaxFail('the channel data holds fewer tracks than its mapping names')
        out.append(ctx.tracks[mark + p])
    return out


def _residual_sfis(r, bases):
    """max_sfb_master and the sf_info of the two residuals after it (Part 1
    4.3.5.13, notes to Tables 25 and 33; see src/ac4dec/ERRATA.md). Residual
    i has the framing of the track its A-CPL module pairs it with, bases[i];
    max_sfb_master is n_side_bits of the largest transform length the two
    base sf_info() signal; a window group of that length takes it as its
    max_sfb, a shorter one Tables B.8 to B.19's value."""
    largest = max(s.largest_len() for s in bases)
    master = r.f(T.N_MSFB_BITS_48[largest][1], 'max_sfb_master')
    residuals = []
    for base in bases:
        m = SfInfo()
        for slot in ('flb', 'long_frame', 'tl', 'tl_len', 'max_sfb', 'max_sfb_side',
                     'b_dual_maxsfb', 'b_side_limited', 'num_windows', 'num_window_groups',
                     'window_to_group', 'num_win_in_group', 'group_tl', 'group_len', 'group_idx'):
            setattr(m, slot, getattr(base, slot))
        override = []
        for g in range(base.num_window_groups):
            length = base.group_len[g]
            if length == largest:
                override.append(master)
            else:
                override.append(T.N_SFB_SIDE[largest][length][master])
        m.master_override = override
        residuals.append(m)
    return residuals


def single_channel_element(r, ctx):
    mode = r.f(1, 'mono_codec_mode')
    _configure(ctx, 'single', mode, mode == 1)
    if ctx.b_iframe and mode == 1:
        aspx_config(r, ctx)
    if mode == 0:
        mono_data(r, ctx, 0)
    else:
        companding_control(r, 1)
        mono_data(r, ctx, 0)
        aspx_data_1ch(r, ctx)


def channel_pair_element(r, ctx):
    mode = r.f(2, 'stereo_codec_mode')
    _configure(ctx, 'pair', mode, mode != 0)
    if ctx.b_iframe:
        if mode == 1:
            aspx_config(r, ctx)
        if mode == 2:
            aspx_config(r, ctx)
            acpl_config_1ch(r, ctx, True)
        if mode == 3:
            aspx_config(r, ctx)
            acpl_config_1ch(r, ctx, False)
    if mode == 0:
        stereo_data(r, ctx)
    elif mode == 1:
        companding_control(r, 2)
        stereo_data(r, ctx)
        aspx_data_2ch(r, ctx)
    elif mode == 2:
        companding_control(r, 1)
        if r.f(1, 'b_enable_mdct_stereo_proc'):
            s = _sfi(r, ctx, 1, 0)
            chparam_info(r, s)
            sm = ss = s
        else:
            _spec_frontend(r, 'spec_frontend_m')
            sm = _sfi(r, ctx, 0, 0)
            _spec_frontend(r, 'spec_frontend_s')
            ss = _sfi(r, ctx, 0, 1)
        sf_data(r, ctx, sm)
        sf_data(r, ctx, ss, side=True)
        aspx_data_1ch(r, ctx)
        acpl_data_1ch(r, ctx)
    else:
        companding_control(r, 1)
        _spec_frontend(r, 'spec_frontend')
        s = _sfi(r, ctx)
        sf_data(r, ctx, s)
        aspx_data_1ch(r, ctx)
        acpl_data_1ch(r, ctx)


def three_0_channel_element(r, ctx):
    mode = r.f(1, '3_0_codec_mode')
    _configure(ctx, '3_0', mode, mode == 1)
    if mode == 1:
        if ctx.b_iframe:
            aspx_config(r, ctx)
        companding_control(r, 3)
    if r.f(1, '3_0_coding_config') == 0:
        stereo_data(r, ctx)
        mono_data(r, ctx, 0)
    else:
        three_channel_data(r, ctx)
    if mode == 1:
        aspx_data_2ch(r, ctx)
        aspx_data_1ch(r, ctx)


def five_x_channel_element(r, ctx, b_has_lfe):
    mode = r.f(3, '5_X_codec_mode')
    if mode > 4:
        raise SyntaxFail(f'5_X_codec_mode {mode} is reserved')
    _configure(ctx, '5_X', mode, mode != 0)
    if ctx.b_iframe:
        if mode in (1, 2, 3, 4):
            aspx_config(r, ctx)
        if mode == 2:
            acpl_config_1ch(r, ctx, True)
        if mode == 3:
            acpl_config_1ch(r, ctx, False)
        if mode == 4:
            acpl_config_2ch(r, ctx)
    if b_has_lfe:
        mono_data(r, ctx, 1)
    if mode in (0, 1):
        if mode == 1:
            companding_control(r, 5)
        cc = r.f(2, 'coding_config')
        if cc == 0:
            r.f(1, '2ch_mode')
            two_channel_data(r, ctx)
            two_channel_data(r, ctx)
            mono_data(r, ctx, 0)
        elif cc == 1:
            three_channel_data(r, ctx)
            two_channel_data(r, ctx)
        elif cc == 2:
            four_channel_data(r, ctx)
            mono_data(r, ctx, 0)
        else:
            five_channel_data(r, ctx)
        if mode == 1:
            aspx_data_2ch(r, ctx)
            aspx_data_2ch(r, ctx)
            aspx_data_1ch(r, ctx)
    elif mode in (2, 3):
        companding_control(r, 3)
        mark = len(ctx.tracks)
        cc = r.f(1, 'coding_config')
        if cc:
            three_channel_data(r, ctx)
        else:
            two_channel_data(r, ctx)
        if mode == 2:
            # Table 181 and Pseudocode 117: the residuals pair with A and B,
            # the channel data's first two tracks.
            m0, m1 = _residual_sfis(r, _tracks_at(ctx, mark, (0, 1)))
            chparam_info(r, m0)
            chparam_info(r, m1)
            sf_data(r, ctx, m0)
            sf_data(r, ctx, m1)
        if cc == 0:
            mono_data(r, ctx, 0)
        aspx_data_2ch(r, ctx)
        aspx_data_1ch(r, ctx)
        acpl_data_1ch(r, ctx)
        acpl_data_1ch(r, ctx)
    else:
        companding_control(r, 2)
        stereo_data(r, ctx)
        aspx_data_2ch(r, ctx)
        acpl_data_2ch(r, ctx)


def seven_x_channel_element(r, ctx, ch_mode):
    mode = r.f(2, '7_X_codec_mode')
    _configure(ctx, '7_X', mode, mode != 0)
    if ctx.b_iframe:
        if mode != 0:
            aspx_config(r, ctx)
        if mode == 2:
            acpl_config_1ch(r, ctx, True)
        if mode == 3:
            acpl_config_1ch(r, ctx, False)
    if ch_mode in (6, 8, 10):
        mono_data(r, ctx, 1)
    if mode in (2, 3):
        companding_control(r, 5)
    mark = len(ctx.tracks)
    cc = r.f(2, 'coding_config')
    two_ch_mode = 0
    if cc == 0:
        two_ch_mode = r.f(1, '2ch_mode')
        two_channel_data(r, ctx)
        two_channel_data(r, ctx)
    elif cc == 1:
        three_channel_data(r, ctx)
        two_channel_data(r, ctx)
    elif cc == 2:
        four_channel_data(r, ctx)
    else:
        five_channel_data(r, ctx)
    # Tracks of A, B (L, R) and D, E (Ls, Rs) in the order the switch read
    # them (Table 182, repeated by Table 184).
    a, b, d, e = 0, 1, 2, 3
    if cc == 0 and two_ch_mode:
        b, d = 2, 1
    elif cc in (1, 3):
        d, e = 3, 4
    back_pair = ch_mode in (5, 6)  # 3/4/0
    if mode in (0, 1):
        if r.f(1, 'b_use_sap_add_ch'):
            # Table 183: F and G are coded against D and E for 3/4/0 and
            # against A and B otherwise; each chparam_info() has that track's
            # framing (see src/ac4dec/ERRATA.md).
            s0, s1 = _tracks_at(ctx, mark, (d, e) if back_pair else (a, b))
            chparam_info(r, s0)
            chparam_info(r, s1)
        two_channel_data(r, ctx)
    if mode == 2:
        # Table 202: the A-CPL modules pair the residuals with Ls and Rs for
        # 3/4/0 or with add_ch_base set, and with L and R otherwise.
        surround = back_pair or ctx.add_ch_base
        m0, m1 = _residual_sfis(r, _tracks_at(ctx, mark, (d, e) if surround else (a, b)))
        chparam_info(r, m0)
        chparam_info(r, m1)
        sf_data(r, ctx, m0)
        sf_data(r, ctx, m1)
    if cc in (0, 2):
        mono_data(r, ctx, 0)
    if mode != 0:
        aspx_data_2ch(r, ctx)
        aspx_data_2ch(r, ctx)
        aspx_data_1ch(r, ctx)
    if mode == 1:
        aspx_data_2ch(r, ctx)
    if mode in (2, 3):
        acpl_data_1ch(r, ctx)
        acpl_data_1ch(r, ctx)


def audio_data_chan(r, ctx, ch_mode):
    """Part 2 6.2.3.1."""
    if ch_mode == 0:
        single_channel_element(r, ctx)
    elif ch_mode == 1:
        channel_pair_element(r, ctx)
    elif ch_mode == 2:
        three_0_channel_element(r, ctx)
    elif ch_mode == 3:
        five_x_channel_element(r, ctx, 0)
    elif ch_mode == 4:
        five_x_channel_element(r, ctx, 1)
    elif 5 <= ch_mode <= 10:
        seven_x_channel_element(r, ctx, ch_mode)
    elif 11 <= ch_mode <= 14:
        raise Refused('immersive_channel_element()')
    elif ch_mode == 15:
        raise Refused('22_2_channel_element()')
    # default: nothing


# ---------------------------------------------------------------------------
# Metadata (Part 2 6.2.7, Part 1 4.2.14)
# ---------------------------------------------------------------------------


def further_loudness_info(r, sus_ver, b_presentation_ldn):
    """Part 2 6.2.7.3."""
    if b_presentation_ldn or sus_ver == 0:
        if r.f(2, 'loudness_version') == 3:
            r.f(4, 'extended_loudness_version')
        if r.f(4, 'loud_prac_type') != 0:
            if r.f(1, 'b_loudcorr_dialgate'):
                r.f(3, 'dialgate_prac_type')
            r.f(1, 'b_loudcorr_type')
    else:
        r.f(1, 'b_loudcorr_dialgate')
    if r.f(1, 'b_loudrelgat'):
        r.f(11, 'loudrelgat')
    if r.f(1, 'b_loudspchgat'):
        r.f(11, 'loudspchgat')
        r.f(3, 'dialgate_prac_type')
    if r.f(1, 'b_loudstrm3s'):
        r.f(11, 'loudstrm3s')
    if r.f(1, 'b_max_loudstrm3s'):
        r.f(11, 'max_loudstrm3s')
    if r.f(1, 'b_truepk'):
        r.f(11, 'truepk')
    if r.f(1, 'b_max_truepk'):
        r.f(11, 'max_truepk')
    if b_presentation_ldn or sus_ver == 0:
        if r.f(1, 'b_prgmbndy'):
            while r.f(1, 'prgmbndy_bit') == 0:
                pass
            r.f(1, 'b_end_or_start')
            if r.f(1, 'b_prgmbndy_offset'):
                r.f(11, 'prgmbndy_offset')
    if r.f(1, 'b_lra'):
        r.f(10, 'lra')
        r.f(3, 'lra_prac_type')
    if r.f(1, 'b_loudmntry'):
        r.f(11, 'loudmntry')
    if r.f(1, 'b_max_loudmntry'):
        r.f(11, 'max_loudmntry')
    if sus_ver >= 1:
        if r.f(1, 'b_rtllcomp'):
            r.f(8, 'rtll_comp')
        if r.f(1, 'b_extension'):
            e = r.f(5, 'e_bits_size')
            if e == 31:
                e += r.vb(4, 'e_bits_size')
            _wide(r, e, 'extensions_bits')
    else:
        if r.f(1, 'b_extension'):
            e = r.f(5, 'e_bits_size')
            if e == 31:
                e += r.vb(4, 'e_bits_size')
            if r.f(1, 'b_rtllcomp'):
                r.f(8, 'rtll_comp')
                _wide(r, e - 9, 'extensions_bits')
            else:
                _wide(r, e - 1, 'extensions_bits')


def _wide(r, n, name):
    """A field the stream sizes and the syntax does not interpret (add_data,
    extensions_bits, drc2_bits): one record of its width, valued at its last
    64 bits. A record's width is 16 bits, so a field longer than 65535 bits is
    recorded as consecutive 65535-bit records, the last shorter."""
    if n < 0:
        raise SyntaxFail(f'{name}: negative width {n}')
    while n > 0:
        width = min(n, 65535)
        pos = r.pos
        v = r._get(width)
        r.recs.append((pos, width, v & _MASK64, name))
        n -= width


def basic_metadata(r, ch_mode, sus_ver):
    """Part 2 6.2.7.2."""
    if sus_ver == 0:
        r.f(7, 'dialnorm_bits')
    if not r.f(1, 'b_more_basic_metadata'):
        return
    if sus_ver == 0:
        if r.f(1, 'b_further_loudness_info'):
            further_loudness_info(r, sus_ver, 0)
    else:
        if r.f(1, 'b_substream_loudness_info'):
            r.f(8, 'substream_loudness_bits')
            if r.f(1, 'b_further_substream_loudness_info'):
                further_loudness_info(r, sus_ver, 0)
    if ch_mode == 1:
        if r.f(1, 'b_prev_dmx_info'):
            r.f(3, 'pre_dmixtyp_2ch')
            r.f(2, 'phase90_info_2ch')
    if ch_mode > 1:
        if sus_ver == 0:
            if r.f(1, 'b_stereo_dmx_coeff'):
                r.f(3, 'loro_centre_mixgain')
                r.f(3, 'loro_surround_mixgain')
                if r.f(1, 'b_loro_dmx_loud_corr'):
                    r.f(5, 'loro_dmx_loud_corr')
                if r.f(1, 'b_ltrt_mixinfo'):
                    r.f(3, 'ltrt_centre_mixgain')
                    r.f(3, 'ltrt_surround_mixgain')
                if r.f(1, 'b_ltrt_dmx_loud_corr'):
                    r.f(5, 'ltrt_dmx_loud_corr')
                if contains_lfe(ch_mode):
                    if r.f(1, 'b_lfe_mixinfo'):
                        r.f(5, 'lfe_mixgain')
                r.f(2, 'preferred_dmx_method')
        if ch_mode in (3, 4):
            if r.f(1, 'b_predmixtyp_5ch'):
                r.f(3, 'pre_dmixtyp_5ch')
            if r.f(1, 'b_preupmixtyp_5ch'):
                r.f(4, 'pre_upmixtyp_5ch')
        if 5 <= ch_mode <= 10:
            if r.f(1, 'b_upmixtyp_7ch'):
                if ch_mode in (5, 6):
                    r.f(2, 'pre_upmixtyp_3_4')
                elif ch_mode in (9, 10):
                    r.f(1, 'pre_upmixtyp_3_2_2')
        r.f(2, 'phase90_info_mc')
        r.f(1, 'b_surround_attenuation_known')
        r.f(1, 'b_lfe_attenuation_known')
    if r.f(1, 'b_dc_blocking'):
        r.f(1, 'dc_block_on')


def extended_metadata(r, ch_mode, sus_ver, b_associated, b_dialog):
    """Part 2 6.2.7.4 (b_associated / b_dialog derived by the caller for sus_ver 0)."""
    if sus_ver >= 1:
        b_dialog = r.f(1, 'b_dialog')
    else:
        if b_associated:
            if r.f(1, 'b_scale_main'):
                r.f(8, 'scale_main')
            if r.f(1, 'b_scale_main_centre'):
                r.f(8, 'scale_main_centre')
            if r.f(1, 'b_scale_main_front'):
                r.f(8, 'scale_main_front')
            if ch_mode == 0:
                r.f(8, 'pan_associated')
    if b_dialog:
        if r.f(1, 'b_dialog_max_gain'):
            r.f(2, 'dialog_max_gain')
        if r.f(1, 'b_pan_dialog_present'):
            if ch_mode == 0:
                r.f(8, 'pan_dialog')
            else:
                r.f(8, 'pan_dialog[0]')
                r.f(8, 'pan_dialog[1]')
                r.f(2, 'pan_signal_selector')
    if r.f(1, 'b_channels_classifier'):
        if contains_c(ch_mode):
            if r.f(1, 'b_c_active'):
                r.f(1, 'b_c_has_dialog')
        if contains_lr(ch_mode):
            if r.f(1, 'b_l_active'):
                r.f(1, 'b_l_has_dialog')
            if r.f(1, 'b_r_active'):
                r.f(1, 'b_r_has_dialog')
        if contains_lsrs(ch_mode):
            r.f(1, 'b_ls_active')
            r.f(1, 'b_rs_active')
        if contains_lbrb(ch_mode):
            r.f(1, 'b_lb_active')
            r.f(1, 'b_rb_active')
        if contains_lwrw(ch_mode):
            r.f(1, 'b_lw_active')
            r.f(1, 'b_rw_active')
        if contains_tfltfr(ch_mode):
            r.f(1, 'b_tfl_active')
            r.f(1, 'b_tfr_active')
        if contains_lfe(ch_mode):
            r.f(1, 'b_lfe_active')
    if r.f(1, 'b_event_probability'):
        r.f(4, 'event_probability')


# -- DRC (Part 1 4.2.14.5-4.2.14.10) ----------------------------------------


def drc_compression_curve(r):
    r.f(4, 'drc_lev_nullband_low')
    r.f(4, 'drc_lev_nullband_high')
    if r.f(4, 'drc_gain_max_boost') > 0:
        r.f(5, 'drc_lev_max_boost')
        if r.f(1, 'drc_nr_boost_sections') > 0:
            r.f(4, 'drc_gain_section_boost')
            r.f(5, 'drc_lev_section_boost')
    if r.f(5, 'drc_gain_max_cut') > 0:
        r.f(6, 'drc_lev_max_cut')
        if r.f(1, 'drc_nr_cut_sections') > 0:
            r.f(5, 'drc_gain_section_cut')
            r.f(5, 'drc_lev_section_cut')
    if not r.f(1, 'drc_tc_default_flag'):
        r.f(8, 'drc_tc_attack')
        r.f(8, 'drc_tc_release')
        r.f(8, 'drc_tc_attack_fast')
        r.f(8, 'drc_tc_release_fast')
        if r.f(1, 'drc_adaptive_smoothing_flag'):
            r.f(5, 'drc_attack_threshold')
            r.f(5, 'drc_release_threshold')


def drc_config(r):
    cfg = {'modes': [], 'curve_flag': {}, 'gains_config': {}}
    nr = r.f(3, 'drc_decoder_nr_modes')
    for _ in range(nr + 1):
        mid = r.f(3, 'drc_decoder_mode_id')
        if mid > 3:
            r.f(5, 'drc_output_level_from')
            r.f(5, 'drc_output_level_to')
        if r.f(1, 'drc_repeat_profile_flag'):
            rid = r.f(3, 'drc_repeat_id')
            if rid not in cfg['curve_flag']:
                raise SyntaxFail(f'drc_repeat_id {rid} names a mode not yet configured')
            cfg['curve_flag'][mid] = cfg['curve_flag'][rid]
            if rid in cfg['gains_config']:
                cfg['gains_config'][mid] = cfg['gains_config'][rid]
        else:
            if not r.f(1, 'drc_default_profile_flag'):
                if r.f(1, 'drc_compression_curve_flag'):
                    cfg['curve_flag'][mid] = 1
                    drc_compression_curve(r)
                else:
                    cfg['curve_flag'][mid] = 0
                    cfg['gains_config'][mid] = r.f(2, 'drc_gains_config')
            else:
                cfg['curve_flag'][mid] = 1
        cfg['modes'].append(mid)
    r.f(3, 'drc_eac3_profile')
    return cfg


def _nr_drc_channels(ch_mode):
    """Part 1 Table 168 and Part 2 Table 69. A mode without LFE takes the count
    of its twin with LFE; 3.0, which has no twin, and a presentation with no
    channel mode have none, so channel-dependent gains there are refused (see
    src/ac4dec/ERRATA.md)."""
    if ch_mode in (0, 1):
        return 1
    if 3 <= ch_mode <= 10:
        return 3
    if 11 <= ch_mode <= 15:
        return 4
    raise Refused(f'channel-dependent DRC gains with no nr_drc_channels for ch_mode {ch_mode}')


def drc_frame(r, b_iframe, state, ch_mode, flb):
    if not r.f(1, 'b_drc_present'):
        # An I-frame that carries no drc_frame() clears the configuration a
        # previous one sent, so a later frame that needs one fails as missing
        # its I-frame (src/ac4dec/ERRATA.md, "Dialogue enhancement and DRC
        # configuration across I-frames").
        if b_iframe:
            state.pop('drc_config', None)
        return
    if b_iframe:
        state['drc_config'] = drc_config(r)
    cfg = state.get('drc_config')
    if cfg is None:
        raise SyntaxFail('drc_data before any drc_config')
    curve_present = 0
    for mid in cfg['modes']:
        flag = cfg['curve_flag'].get(mid)
        if flag == 0:
            size = r.f(6, 'drc_gainset_size_value')
            if r.f(1, 'b_more_bits'):
                size += r.vb(2, 'variable_bits') << 6
            version = r.f(2, 'drc_version')
            used = 0
            if version <= 1:
                start = r.pos
                r.f(7, 'drc_gain_val')
                if cfg['gains_config'].get(mid, 0) > 0:
                    n_ch = _nr_drc_channels(ch_mode)
                    n_bands = T.NR_DRC_BANDS[cfg['gains_config'][mid]]
                    n_sf = T.NR_DRC_SUBFRAMES[flb]
                    for ch in range(n_ch):
                        for band in range(n_bands):
                            for sf in range(n_sf):
                                if sf != 0 or band != 0 or ch != 0:
                                    CB['DRC_HCB'].decode(r, 'drc_gain_code')
                used = r.pos - start
            # Version 0 reads nothing by the size, which the text counts both
            # with and without drc_version; any other size is a misread (see
            # src/ac4dec/ERRATA.md).
            if version == 0 and size not in (used, used + 2):
                raise SyntaxFail(f'drc_gainset_size {size} does not match the {used} bits read')
            if version >= 1:
                _wide(r, size - 2 - used, 'drc2_bits')
        elif flag == 1:
            curve_present = 1
    if curve_present:
        r.f(1, 'drc_reset_flag')
        r.f(2, 'drc_reserved')


# -- dialogue enhancement (Part 2 6.2.7.5/6.2.7.6, Part 1 4.2.14.12) ---------


def de_data(r, cfg, b_iframe, b_de_simulcast):
    method = cfg['de_method']
    nch = T.DE_NR_CHANNELS[cfg['de_channel_config']]
    if nch == 0:
        return
    if method in (1, 3) and nch > 1:
        if b_de_simulcast == 0:
            keep_pos = 0 if b_iframe else r.f(1, 'de_keep_pos_flag')
            if keep_pos == 0:
                r.f(5, 'de_mix_coef1_idx')
                if nch == 3:
                    r.f(5, 'de_mix_coef2_idx')
    keep_data = 0 if b_iframe else r.f(1, 'de_keep_data_flag')
    if keep_data == 0:
        ms = 0
        if method in (0, 2) and nch == 2:
            ms = r.f(1, 'de_ms_proc_flag')
        tbl = method % 2
        abs_cb = CB[f'DE_HCB_ABS_{tbl}']
        diff_cb = CB[f'DE_HCB_DIFF_{tbl}']
        for ch in range(nch - ms):
            if b_iframe and ch == 0:
                abs_cb.decode(r, 'de_par_code')
                for _ in range(1, 8):
                    diff_cb.decode(r, 'de_par_code')
            else:
                for _ in range(8):
                    diff_cb.decode(r, 'de_par_code')
        if method >= 2:
            r.f(5, 'de_signal_contribution')


def dialog_enhancement(r, b_iframe, ch_mode, state):
    if not r.f(1, 'b_de_data_present'):
        # Same I-frame rule as drc_frame() above.
        if b_iframe:
            state.pop('de_config', None)
        return
    # de_config() in I-frames, else when b_de_config_flag (read only outside I-frames)
    if b_iframe or r.f(1, 'b_de_config_flag'):
        state['de_config'] = {'de_method': r.f(2, 'de_method'),
                              'de_max_gain': r.f(2, 'de_max_gain'),
                              'de_channel_config': r.f(3, 'de_channel_config')}
    cfg = state.get('de_config')
    if cfg is None:
        raise SyntaxFail('de_data before any de_config')
    de_data(r, cfg, b_iframe, 0)
    if ch_mode in (13, 14):
        if r.f(1, 'b_de_simulcast'):
            de_data(r, cfg, b_iframe, 1)


# -- EMDF (Part 1 4.2.4.4, 4.2.14.14) -----------------------------------------


def emdf_payload_config(r):
    smp = r.f(1, 'b_smpoffst')
    if smp:
        r.vb(11, 'smpoffst')
    if r.f(1, 'b_duration'):
        r.vb(11, 'duration')
    if r.f(1, 'b_groupid'):
        r.vb(2, 'groupid')
    if r.f(1, 'b_codecdata'):
        r.f(8, 'codecdata')
    if not r.f(1, 'b_discard_unknown_payload'):
        aligned = 0
        if smp == 0:
            aligned = r.f(1, 'b_payload_frame_aligned')
            if aligned:
                r.f(1, 'b_create_duplicate')
                r.f(1, 'b_remove_duplicate')
        if smp == 1 or aligned == 1:
            r.f(5, 'priority')
            r.f(2, 'proc_allowed')


def emdf_payloads_substream(r, align_base=0):
    while True:
        pid = r.f(5, 'emdf_payload_id')
        if pid == 0:
            break
        if pid == 31:
            r.vb(5, 'emdf_payload_id')
        emdf_payload_config(r)
        size = r.vb(8, 'emdf_payload_size')
        if r.pos + 8 * size > r.end:
            raise SyntaxFail(f'emdf_payload_size {size} runs past the end of the substream')
        for _ in range(size):
            r.f(8, 'emdf_payload_byte')
    r.align(align_base)


def metadata(r, ctx, sus_ver, b_alternative, b_ajoc, b_associated=0, b_dialog=0):
    """Part 2 6.2.7.1; checks tools_metadata_size."""
    basic_metadata(r, ctx.ch_mode, sus_ver)
    extended_metadata(r, ctx.ch_mode, sus_ver, b_associated, b_dialog)
    # oamd_dyndata_single() is read for b_alternative with b_ajoc 0, but it
    # belongs to object substreams, which are refused before metadata(); a
    # channel-coded substream carries none (see src/ac4dec/ERRATA.md).
    tms = r.f(7, 'tools_metadata_size_value')
    if r.f(1, 'b_more_bits'):
        tms += r.vb(3, 'variable_bits') << 7
    start = r.pos
    if sus_ver == 0:
        drc_frame(r, ctx.b_iframe, ctx.state, ctx.ch_mode, ctx.flb)
    dialog_enhancement(r, ctx.b_iframe, ctx.ch_mode, ctx.state)
    used = r.pos - start
    if used != tms:
        raise SyntaxFail(f'tools metadata used {used} bits, tools_metadata_size says {tms}')
    if r.f(1, 'b_emdf_payloads_substream'):
        emdf_payloads_substream(r)


# ---------------------------------------------------------------------------
# Substreams
# ---------------------------------------------------------------------------


def parse_ac4_substream(data, info, b_iframe, flb, state, recs, b_alternative, sus_ver,
                        b_associated=0, b_dialog=0):
    """Part 2 6.2.2.2 for a channel-coded substream."""
    r = Reader(data, recs)
    audio_size = r.f(15, 'audio_size_value')
    if r.f(1, 'b_more_bits'):
        audio_size += r.vb(7, 'variable_bits') << 15
    if info.get('sf_multiplier') is not None:
        raise Refused('substream sampling frequency multiplier (96/192 kHz)')
    r.align()  # Part 1 Table 16 byte_align; a no-op after 16 (+ 8k) bits
    audio_start = r.pos
    audio_end = audio_start + 8 * audio_size
    if audio_end > r.end:
        raise SyntaxFail(f'audio_size {audio_size} runs past the substream ({r.end // 8} bytes)')
    ctx = AudioCtx(flb, b_iframe, state, info['ch_mode'], info.get('add_ch_base', 0))
    audio_data_chan(r, ctx, info['ch_mode'])
    if r.pos > audio_end:
        raise SyntaxFail(f'audio_data ends at bit {r.pos}, beyond audio_size end {audio_end}')
    r.pos = audio_end  # fill_bits, byte_align
    metadata(r, ctx, sus_ver, b_alternative, 0, b_associated, b_dialog)
    r.align()
    if r.pos != r.end:
        raise SyntaxFail(f'ac4_substream ends at byte {r.pos // 8}, substream_size is {r.end // 8}')


def custom_dmx_data(r, pc):
    pcm, pcmc = pc['pres_ch_mode'], pc['pres_ch_mode_core']
    b4 = pc['b_pres_4_back_channels_present']
    tops = pc['pres_top_channel_pairs']
    lfe = pc['b_pres_has_lfe']
    bs = -1
    if pcm in (11, 12, 13, 14):
        if tops == 2:
            if pcm >= 13 and b4 == 1:
                bs = 0
            if pcm <= 12:
                bs = 1 if b4 == 1 else 2
        if tops == 1:
            if pcm >= 13 and b4 == 1:
                bs = 3
            if pcm <= 12:
                bs = 4 if b4 == 1 else 5
    if bs >= 0:
        if r.f(1, 'b_cdmx_data_present'):
            n = r.f(2, 'n_cdmx_configs_minus1') + 1
            for _ in range(n):
                occ = r.f(1 if bs in (2, 5) else 3, 'out_ch_config')
                cdmx_parameters(r, bs, occ)
    if pcm >= 3 or pcmc >= 3:
        if r.f(1, 'b_stereo_dmx_coeff'):
            r.f(3, 'loro_centre_mixgain')
            r.f(3, 'loro_surround_mixgain')
            if r.f(1, 'b_ltrt_mixinfo'):
                r.f(3, 'ltrt_centre_mixgain')
                r.f(3, 'ltrt_surround_mixgain')
            if lfe == 1:
                if r.f(1, 'b_lfe_mixinfo'):
                    r.f(5, 'lfe_mixgain')
            r.f(2, 'preferred_dmx_method')


def _tool_scr_to_c_l(r):
    if r.f(1, 'b_put_screen_to_c'):
        r.f(3, 'gain_f1_code')
    else:
        r.f(3, 'gain_f2_code')


def _tool_b4_to_b2(r):
    r.f(3, 'gain_b_code')


def _tool_t4_to_t2(r):
    r.f(3, 'gain_t1_code')


def _tool_t4_to_f_s_b(r):
    if r.f(1, 'b_top_front_to_front'):
        r.f(3, 'gain_t2a_code')
    elif r.f(1, 'b_top_front_to_side'):
        r.f(3, 'gain_t2b_code')
    else:
        r.f(3, 'gain_t2c_code')
    if r.f(1, 'b_top_back_to_front'):
        r.f(3, 'gain_t2d_code')
    elif r.f(1, 'b_top_back_to_side'):
        r.f(3, 'gain_t2e_code')
    else:
        r.f(3, 'gain_t2f_code')


def _tool_t4_to_f_s(r):
    if r.f(1, 'b_top_front_to_front'):
        r.f(3, 'gain_t2a_code')
    else:
        r.f(3, 'gain_t2b_code')
    if r.f(1, 'b_top_back_to_front'):
        r.f(3, 'gain_t2d_code')
    else:
        r.f(3, 'gain_t2e_code')


def _tool_t2_to_f_s_b(r):
    if r.f(1, 'b_top_to_front'):
        r.f(3, 'gain_t2a_code')
    elif r.f(1, 'b_top_to_side'):
        r.f(3, 'gain_t2b_code')
    else:
        r.f(3, 'gain_t2c_code')


def _tool_t2_to_f_s(r):
    if r.f(1, 'b_top_to_front'):
        r.f(3, 'gain_t2a_code')
    else:
        r.f(3, 'gain_t2b_code')


def cdmx_parameters(r, bs, occ):
    if bs in (0, 3):
        _tool_scr_to_c_l(r)
    if bs < 2:
        if occ == 0:
            _tool_t4_to_f_s(r)
            _tool_b4_to_b2(r)
        elif occ == 1:
            _tool_t4_to_t2(r)
            _tool_b4_to_b2(r)
        elif occ == 2:
            _tool_b4_to_b2(r)
        elif occ == 3:
            _tool_t4_to_f_s_b(r)
        elif occ == 4:
            _tool_t4_to_t2(r)
    if bs == 2:
        if occ == 0:
            _tool_t4_to_f_s(r)
        elif occ == 1:
            _tool_t4_to_t2(r)
    if 3 <= bs <= 4:
        if occ == 0:
            _tool_t2_to_f_s(r)
            _tool_b4_to_b2(r)
        elif occ in (1, 2):
            _tool_b4_to_b2(r)
        elif occ == 3:
            _tool_t2_to_f_s_b(r)
    if bs == 5:
        if occ == 0:
            _tool_t2_to_f_s(r)


def loud_corr(r, pcm, pcmc, b_objects):
    obj = r.f(1, 'b_obj_loud_corr') if b_objects == 1 else 0
    imm = 0
    if pcm > 4 or obj == 1:
        imm = r.f(1, 'b_corr_for_immersive_out')
    if pcm > 1 or obj == 1:
        if r.f(1, 'b_loro_loud_comp'):
            r.f(5, 'loro_dmx_loud_corr')
        if r.f(1, 'b_ltrt_loud_comp'):
            r.f(5, 'ltrt_dmx_loud_corr')
    if pcm > 4 or obj == 1:
        if r.f(1, 'b_loud_comp'):
            r.f(5, 'loud_corr_5_X')
        if imm == 1:
            if r.f(1, 'b_loud_comp'):
                r.f(5, 'loud_corr_5_X_2')
            if r.f(1, 'b_loud_comp'):
                r.f(5, 'loud_corr_7_X')
    if pcm > 10 or obj == 1:
        if imm == 1:
            if r.f(1, 'b_loud_comp'):
                r.f(5, 'loud_corr_7_X_4')
            if r.f(1, 'b_loud_comp'):
                r.f(5, 'loud_corr_7_X_2')
            if r.f(1, 'b_loud_comp'):
                r.f(5, 'loud_corr_5_X_4')
    if pcmc >= 5:
        if r.f(1, 'b_loud_comp'):
            r.f(5, 'loud_corr_core_5_X_2')
    if pcmc >= 3:
        if r.f(1, 'b_loud_comp'):
            r.f(5, 'loud_corr_core_5_X')
        if r.f(1, 'b_loud_comp'):
            r.f(5, 'loud_corr_core_loro')
            r.f(5, 'loud_corr_core_ltrt')
    if obj == 1:
        if r.f(1, 'b_loud_comp'):
            r.f(5, 'loud_corr_9_X_4')


def parse_presentation_substream(data, pc, flb, state, recs):
    """Part 2 6.2.2.3."""
    r = Reader(data, recs)
    if pc['b_alternative']:
        if r.f(1, 'b_name_present'):
            name_len = r.f(5, 'name_len') if r.f(1, 'b_length') else 32
            for _ in range(name_len):
                r.f(8, 'presentation_name')
        n_targets = r.f(2, 'n_targets_minus1') + 1
        if n_targets == 4:
            n_targets += r.vb(2, 'variable_bits')
        for _ in range(n_targets):
            r.f(3, 'target_level')
            r.f(4, 'target_device_category[]')
            if r.f(1, 'b_tdc_extension') == 1:
                r.f(4, 'reserved_bits')
            if r.f(1, 'b_ducking_depth_present'):
                r.f(6, 'max_ducking_depth')
            if r.f(1, 'b_loud_corr_target'):
                r.f(5, 'loud_corr_target')
            for _ in range(pc['n_substreams_in_presentation']):
                if r.f(1, 'b_active'):
                    if r.f(1, 'alt_data_set_index') == 1:
                        r.vb(2, 'variable_bits')
    if r.f(1, 'b_additional_data'):
        add_bytes = r.f(4, 'add_data_bytes_minus1') + 1
        if add_bytes == 16:
            add_bytes += r.vb(2, 'variable_bits')
        r.align()
        bits = add_bytes * 8
        r.f(1, 'immersive_audio_indicator')
        bits -= 1
        if pc['pres_ch_mode'] == -1:
            r.f(1, 'b_oamd_common_timing')
            bits -= 1
        b_advanced_de_data_present = r.f(1, 'b_advanced_de_data_present')
        bits -= 1
        if b_advanced_de_data_present:
            start = r.pos
            if r.f(1, 'b_advanced_de_config_present'):
                r.f(6, 'advanced_de_compr_tc_attack')
                r.f(6, 'advanced_de_compr_tc_release')
                r.f(4, 'advanced_de_compr_ratio')
            r.f(6, 'advanced_de_compr_thresh')
            r.f(5, 'advanced_de_compr_gain')
            bits -= r.pos - start
        if bits < 0:
            raise SyntaxFail(f'additional data overruns add_data_bytes by {-bits} bits')
        _wide(r, bits, 'add_data')
    r.f(7, 'dialnorm_bits')
    if r.f(1, 'b_further_loudness_info'):
        further_loudness_info(r, 1, 1)
    size = r.f(5, 'drc_metadata_size_value')
    if r.f(1, 'b_more_bits') == 1:
        size += r.vb(3, 'variable_bits') << 5
    start = r.pos
    drc_frame(r, pc['b_pres_ndot'], state, pc['pres_ch_mode'], flb)
    if r.pos - start != size:
        raise SyntaxFail(f'drc_frame used {r.pos - start} bits, drc_metadata_size says {size}')
    if pc['n_substream_groups'] > 1:
        if r.f(1, 'b_substream_group_gains_present') == 1:
            if r.f(1, 'b_keep') == 0:
                for _ in range(pc['n_substream_groups']):
                    r.f(6, 'sg_gain')
    if r.f(1, 'b_associated') == 1:
        if r.f(1, 'b_scale_main') == 1:
            r.f(8, 'scale_main')
        if r.f(1, 'b_scale_main_centre') == 1:
            r.f(8, 'scale_main_centre')
        if r.f(1, 'b_scale_main_front') == 1:
            r.f(8, 'scale_main_front')
        if r.f(1, 'b_associate_is_mono') == 1:
            r.f(8, 'pan_associated')
    custom_dmx_data(r, pc)
    loud_corr(r, pc['pres_ch_mode'], pc['pres_ch_mode_core'], 1 if pc['pres_ch_mode'] == -1 else 0)
    r.align()
    if r.pos != r.end:
        raise SyntaxFail(f'ac4_presentation_substream ends at byte {r.pos // 8}, '
                         f'substream_size is {r.end // 8}')


def parse_emdf_payloads(data, recs):
    r = Reader(data, recs)
    emdf_payloads_substream(r)
    if r.pos != r.end:
        raise SyntaxFail(f'emdf_payloads_substream ends at byte {r.pos // 8}, '
                         f'substream_size is {r.end // 8}')


# ---------------------------------------------------------------------------
# Frame walk (TOC from ac4_parse)
# ---------------------------------------------------------------------------

IMS_STEREO_CODE = 0b1111000


def _groups_of(toc, p):
    """The ac4_substream_group_info() dicts a presentation references
    (group_index for bitstream_version 2, inline dicts for version 1), each
    once. A presentation may name one group twice; the group holds the same
    substreams either way, so the helpers of 6.3.3.1.29 to 6.3.3.1.31 count
    them once (src/ac4dec/ERRATA.md, 'A substream group named twice')."""
    groups = toc.get('substream_groups') or []
    out = []
    for ref in p.get('group_refs', []):
        if isinstance(ref, int):
            if ref < len(groups):
                g = groups[ref]
            else:
                continue
        else:
            g = ref
        if not any(g is seen for seen in out):
            out.append(g)
    return out


def presentation_context(toc, p):
    """Part 2 6.3.3.1.13 and 6.3.3.1.27-31 helper variables."""
    pcm = -1
    pcmc = -1
    obj = 0
    adaptive = 0
    b4 = 0
    top_pairs = 0
    n_subs = 0
    for g in _groups_of(toc, p):
        for s in g['substreams']:
            info = s['info']
            n_subs += 1
            if g['b_channel_coded']:
                cm = info['ch_mode']
                if cm is not None:
                    pcm = superset(pcm, cm)
                    core = 5 if cm in (11, 13) else 6 if cm in (12, 14) else -1
                    pcmc = superset(pcmc, core, _CORE_SETS)
                oc = info.get('original_content') or {}
                if oc:
                    b4 = b4 or int(oc['b_4_back_channels_present'])
                    tcp = oc['top_channels_present']
                    top_pairs = max(top_pairs, 2 if tcp == 3 else 1 if tcp in (1, 2) else 0)
            else:
                obj = 1
                if s['kind'] == 'ajoc' and info['b_static_dmx']:
                    pcmc = superset(pcmc, 4 if info['b_lfe'] else 3, _CORE_SETS)
                else:
                    adaptive = 1
    for _, info in p.get('substreams', []):  # presentation_version 0 (Part 1 Table 5)
        n_subs += 1
        if info['ch_mode'] is not None:
            pcm = superset(pcm, info['ch_mode'])
    if obj:
        pcm = -1
    if adaptive:
        pcmc = -1
    if pcmc == pcm:
        pcmc = -1
    has_lfe = int(contains_lfe(pcm)) if pcm >= 0 else int(pcmc in (4, 6))
    ps = p.get('presentation_substream') or {}
    return {'pres_ch_mode': pcm, 'pres_ch_mode_core': pcmc, 'b_pres_4_back_channels_present': b4,
            'pres_top_channel_pairs': top_pairs, 'b_pres_has_lfe': has_lfe,
            'n_substreams_in_presentation': n_subs,
            'n_substream_groups': p.get('n_substream_groups', 1),
            'b_alternative': ps.get('b_alternative', 0), 'b_pres_ndot': ps.get('b_pres_ndot', 0)}


def substream_roles(toc):
    """substream index -> (kind, details); the first referencing info element
    in TOC order decides (Part 1 Table 15, Part 2 Table 50)."""
    roles = {}

    def put(idx, role):
        if idx is not None and idx not in roles:
            roles[idx] = role

    def audio(info, sus_ver, kind, owner, frames_key):
        idx = info.get('substream_index')
        if idx is None:
            return
        # 4.3.3.7.9: with a frame rate factor above 1 the element names a
        # series of consecutive substreams. They are consecutive codec frames
        # of one signal (4.3.3.5.3), and b_iframe_global answers to the first
        # of them (4.3.3.2.7), so they share the first instance's carried
        # state and each covers frame_len_base / factor samples.
        frames = info.get(frames_key) or [0]
        for i, ndot in enumerate(frames):
            put(idx + i, ('audio', {'info': info, 'sus_ver': sus_ver, 'kind': kind,
                                    'b_iframe': ndot, 'owner': owner,
                                    'state_key': idx, 'frame_rate_factor': len(frames)}))

    pres = toc['presentations']
    for p in pres:
        for e in [p.get('emdf'), *(p.get('emdf_substreams') or [])]:
            if e:
                put(e.get('payloads_substream_index'), ('emdf_payloads', p))
        ps = p.get('presentation_substream')
        if ps:
            put(ps['substream_index'], ('presentation', p))
        for _, info in p.get('substreams', []):
            audio(info, 0, 'chan', p, 'b_iframe')
            put(info.get('hsf_ext_substream_index'), ('hsf_ext', p))
    seen = []
    for p in pres:
        for g in _groups_of(toc, p):
            if any(g is x for x in seen):
                continue
            seen.append(g)
            if g.get('oamd') and g['oamd'].get('substream_index') is not None:
                put(g['oamd']['substream_index'], ('oamd', g))
            for s in g['substreams']:
                audio(s['info'], s['sus_ver'], s['kind'], p, 'b_audio_ndot')
                put(s.get('hsf_ext_substream_index'), ('hsf_ext', g))
    return roles


def apply_ims_rule(toc):
    """The observed rule (src/ac4dec/ERRATA.md): in a presentation_version 2 presentation,
    channel_mode 0b1111000 is read as stereo (ch_mode 1)."""
    for p in toc['presentations']:
        if p.get('presentation_version') != 2:
            continue
        for g in _groups_of(toc, p):
            if g['b_channel_coded']:
                for s in g['substreams']:
                    if s['info']['channel_mode'] == IMS_STEREO_CODE:
                        s['info']['ch_mode'] = 1


def _derive_assoc_dialog(p, info):
    """Part 1 4.3.12.4.1 / 4.3.12.4.2 for sus_ver 0 (src/ac4dec/ERRATA.md)."""
    cfg = p.get('presentation_config')
    subs = [x for _, x in p.get('substreams', [])]
    pos = next((i for i, x in enumerate(subs) if x is info), -1)
    cc = (info.get('content_type') or {}).get('content_classifier')
    assoc = 1 if cc in (0b101, 0b011, 0b010) else 0
    if (cfg == 2 and pos == 1) or (cfg in (3, 4) and pos == 2):
        assoc = 1
    dialog = 1 if (cfg in (0, 3) and pos == 1) or cc == 0b100 else 0
    return assoc, dialog


class StreamWalker:
    """Walks sync frames; configuration sent in I-frames persists per
    (kind, substream index) across frames."""

    def __init__(self, ims_rule=True):
        self.ims_rule = ims_rule
        self.state = {}
        self.previous_counter = None

    def frame(self, raw):
        """Returns [(index, kind, recs, error_or_None)] for one raw_ac4_frame()."""
        r = ac4_parse.Reader(raw)
        toc = ac4_parse.parse_ac4_toc(r)
        # Part 1 4.3.3.2.2: the stream continues when sequence_counter is the
        # previous value plus 1, wraps from 1020 to 1, or follows a 0; anything
        # else is a change of source, after which nothing carried is used.
        counter, previous = toc['sequence_counter'], self.previous_counter
        if previous is not None and not (counter == previous + 1
                                         or (counter == 1 and previous == 1020)
                                         or (counter != 0 and previous == 0)):
            self.state.clear()
        if self.ims_rule:
            apply_ims_rule(toc)
        # Tables 83 and 84: index 13 is the only frame rate Table 84 defines at
        # 44.1 kHz, so every other index there has no frame length, the way the
        # decoder's frame_len_base() reads the pair.
        if toc['fs_index'] == 0 and toc['frame_rate_index'] != 13:
            flb = None
        else:
            flb = T.FRAME_LEN_BASE.get(toc['frame_rate_index'])
        # Part 2 5.1.3: with frame_rate_fraction above 1 a coded frame is spread
        # over 2 or 4 transmission frames, so this frame holds fragments rather
        # than whole substreams. Assembling them is out of scope, and reading a
        # fragment as a substream would report a legal stream as a damaged one,
        # so every substream of such a frame is refused, as the decoder does.
        fragmented = any(p.get('frame_rate_fraction', 1) != 1 for p in toc['presentations'])
        roles = substream_roles(toc)
        out = []
        offset = toc['toc_bytes'] + toc['payload_base']
        sizes = toc['substream_sizes'] if toc['b_size_present'] else [max(0, len(raw) - offset)]
        # Substreams that run past the frame make the frame's table of
        # contents wrong, so none of them is read.
        end = offset
        for size in sizes:
            end += size
            if end > len(raw):
                raise ValueError(
                    f'substreams run past the end of the frame ({end} > {len(raw)} bytes)')
        # Only a frame that parses this far counts as the predecessor of the
        # next one: the decoder takes its counter from ac4::parse_raw_frame(),
        # which reports no table of contents at all when the substreams overrun,
        # so a frame rejected here leaves the counter where it was and the next
        # frame reads as a change of source (src/ac4dec/ERRATA.md, "A change of
        # source").
        self.previous_counter = counter
        for idx, size in enumerate(sizes):
            data = raw[offset:offset + size]
            offset += size
            role = roles.get(idx)
            kind = role[0] if role else 'unreferenced'
            recs = []
            err = None
            try:
                if len(data) != size:
                    raise SyntaxFail(f'substream {idx} ({size} bytes) runs past the end of '
                                     'the frame')
                if fragmented:
                    raise Refused('a frame of the efficient high frame rate mode, whose '
                                  'substreams are fragments')
                if kind == 'presentation':
                    # The same reserved-frame-rate check the audio branch
                    # makes below: without it a frame length of None reaches
                    # the DRC subframe table as a key, and the KeyError is
                    # caught by neither handler - it ends the whole walk
                    # instead of this one substream. The decoder refuses it
                    # per substream (nr_drc_subframes of a frame length
                    # Table 169 does not list).
                    if flb is None:
                        raise SyntaxFail(f'frame_rate_index {toc["frame_rate_index"]} is reserved')
                    pc = presentation_context(toc, role[1])
                    st = self.state.setdefault(('presentation', idx), {})
                    parse_presentation_substream(data, pc, flb, st, recs)
                elif kind == 'emdf_payloads':
                    parse_emdf_payloads(data, recs)
                elif kind == 'audio':
                    a = role[1]
                    info = a['info']
                    if a['kind'] != 'chan':
                        raise Refused(f'{a["kind"]} substream (object audio)')
                    if info['ch_mode'] is None:
                        raise Refused(f'reserved channel_mode {info["channel_mode"]:#b}')
                    if flb is None:
                        raise SyntaxFail(f'frame_rate_index {toc["frame_rate_index"]} is reserved')
                    owner = a['owner']
                    ps = owner.get('presentation_substream') if owner else None
                    b_alt = ps['b_alternative'] if ps else 0
                    b_assoc = b_dlg = 0
                    if a['sus_ver'] == 0 and owner is not None:
                        b_assoc, b_dlg = _derive_assoc_dialog(owner, info)
                    # The slot is the series' first index, this substream's own
                    # outside a frame-rate-multiplied series; every instance of
                    # a series carries one state, and each covers its share of
                    # the base frame (substream_roles()'s own comment).
                    st = self.state.setdefault(('audio', a['state_key']), {})
                    # What a substream carries between frames belongs to its
                    # channel mode and substream version; a change of either
                    # starts it afresh.
                    if st.get('carried_for') != (info['ch_mode'], a['sus_ver']):
                        st.clear()
                        st['carried_for'] = (info['ch_mode'], a['sus_ver'])
                    factor = a['frame_rate_factor']
                    if factor <= 0 or flb % factor:
                        raise SyntaxFail(f'frame_rate_factor {factor} does not divide '
                                         f'frame_len_base {flb}')
                    parse_ac4_substream(data, info, a['b_iframe'], flb // factor, st, recs, b_alt,
                                        a['sus_ver'], b_assoc, b_dlg)
                elif kind in ('hsf_ext', 'oamd'):
                    raise Refused(f'{kind} substream')
            except Refused as exc:
                err = f'refused: {exc}'
            except SyntaxFail as exc:
                err = f'FAIL: {exc}'
            out.append((idx, 'audio' if kind in ('audio', 'hsf_ext', 'oamd') else kind, recs, err))
        return out


def walk_stream(data, ims_rule=True, diagnostics=None):
    """Yields (frame, substream, kind, records) for every substream with at
    least one record, in frame and substream order. Refusals, invariant
    failures and TOC errors are appended to `diagnostics` (a list) if given."""
    walker = StreamWalker(ims_rule)
    frames = ac4_parse.iter_sync_frames(data)
    fi = -1
    while True:
        try:
            _, _, raw, crc_ok = next(frames)
        except StopIteration:
            return
        except (ValueError, IndexError) as exc:
            if diagnostics is not None:
                diagnostics.append(f'sync after frame {fi}: FAIL: {exc}')
            return
        fi += 1
        if crc_ok is False and diagnostics is not None:
            diagnostics.append(f'frame {fi}: FAIL: CRC mismatch')
        try:
            subs = walker.frame(raw)
        except (ValueError, IndexError) as exc:
            if diagnostics is not None:
                diagnostics.append(f'frame {fi}: TOC: FAIL: {exc}')
            continue
        for idx, kind, recs, err in subs:
            if err and diagnostics is not None:
                diagnostics.append(f'frame {fi} substream {idx} ({kind}): {err}')
            if recs:
                yield fi, idx, kind, recs


def digest_line(frame, idx, kind, recs):
    crc = 0
    pack = _PACK
    buf = bytearray()
    for pos, width, value, _ in recs:
        buf += pack(pos, width, value)
        if len(buf) > 65536:
            crc = zlib.crc32(buf, crc)
            buf.clear()
    crc = zlib.crc32(buf, crc)
    last = recs[-1]
    return f'{frame}\t{idx}\t{kind}\t{len(recs)}\t{last[0] + last[1]}\t0x{crc:08x}'


DIGEST_COLUMNS = '# frame\tsubstream\tkind\trecords\tend_bit\tcrc32'


def digest_lines(data: bytes, stream_name: str, ims_rule=True, diagnostics=None) -> list[str]:
    """The digest file's lines (trace contract, 'Digests'), without newlines."""
    lines = [f'# ac4-syntax-digest/1 {stream_name}', DIGEST_COLUMNS]
    for fi, idx, kind, recs in walk_stream(data, ims_rule, diagnostics):
        lines.append(digest_line(fi, idx, kind, recs))
    return lines


def stream_label(path):
    """Path relative to tests/golden/external-baseline/ when inside it, else the file name."""
    p = Path(path).resolve().as_posix()
    marker = '/tests/golden/external-baseline/'
    if marker in p:
        return p.split(marker, 1)[1]
    return Path(path).name


def run(argv):
    ims_rule = True
    args = list(argv)
    if args and args[0] == '--literal-ims':
        ims_rule = False
        args = args[1:]
    if len(args) < 2 or args[0] not in ('digest', 'trace'):
        sys.stderr.write(__doc__)
        return 2
    cmd, path = args[0], args[1]
    data = Path(path).read_bytes()
    label = stream_label(path)
    diagnostics = []
    out = sys.stdout
    if cmd == 'digest':
        for line in digest_lines(data, label, ims_rule, diagnostics):
            out.write(line + '\n')
    else:
        first, last = 0, None
        if len(args) >= 4:
            first, last = int(args[2]), int(args[3])
        for fi, idx, _kind, recs in walk_stream(data, ims_rule, diagnostics):
            if last is not None and fi > last:
                break
            if fi >= first:
                out.write(''.join(f'{fi}\t{idx}\t{p}\t{w}\t{v}\t{n}\n' for p, w, v, n in recs))
    fails = [d for d in diagnostics if 'FAIL' in d]
    for d in diagnostics:
        sys.stderr.write(d + '\n')
    sys.stderr.write(f'{label}: {len(fails)} failures, {len(diagnostics) - len(fails)} refusals\n')
    return 1 if fails else 0


if __name__ == '__main__':
    sys.exit(run(sys.argv[1:]))
