#!/usr/bin/env python3
"""Generate the documentation support matrices from one JSON catalogue.

The home-page selector reads docs/assets/data/support-catalogue.json directly.
This script turns the comparison sections of that catalogue into committed
Markdown snippets, keeping the searchable, no-JavaScript tables on the same
source. Run with --check in CI to detect stale generated files.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

CATALOGUE = Path("docs/assets/data/support-catalogue.json")
GENERATED = Path("docs-snippets/generated")


def _load(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("support catalogue schema_version must be 1")
    return data


def _escape(value: str) -> str:
    return value.replace("|", "&#124;").replace("\n", " ")


def _cell(
    value: list[str], states: dict[str, Any], evidence: dict[str, str]
) -> str:
    if len(value) != 3:
        raise ValueError(f"matrix cell must have [state, evidence, note]: {value!r}")
    state_id, evidence_id, note = value
    if state_id not in states:
        raise ValueError(f"unknown support state: {state_id}")
    if evidence_id not in evidence:
        raise ValueError(f"unknown evidence state: {evidence_id}")

    state = states[state_id]["label"]
    parts = [f"**{_escape(state)}**"]
    qualifier = evidence[evidence_id]
    if qualifier:
        parts.append(_escape(qualifier))
    if note:
        parts.append(_escape(note))
    return "<br>".join(parts)


def _relative_link(target: str, containing_page: str) -> str:
    base = Path(containing_page).parent
    return Path(os.path.relpath(Path(target), base)).as_posix()


def _header() -> str:
    return (
        "<!-- Generated by tools/checks/generate_support_matrices.py from "
        "docs/assets/data/support-catalogue.json. Do not edit by hand. -->\n\n"
    )


def render_overview(
    data: dict[str, Any], matrix_key: str, first_column: str
) -> str:
    groups = data["platform_groups"]
    group_ids = [group["id"] for group in groups]
    states = data["states"]
    evidence = data["evidence"]
    containing_page = "platforms/index.md"

    lines = [
        f"| {first_column} | "
        + " | ".join(
            f"[{_escape(group['label'])}]"
            f"({_relative_link(group['page'], containing_page)})"
            for group in groups
        )
        + " |",
        "|" + "---|" * (len(groups) + 1),
    ]
    for row in data[matrix_key]:
        missing = set(group_ids) - set(row["cells"])
        extra = set(row["cells"]) - set(group_ids)
        if missing or extra:
            raise ValueError(
                f"overview row {row['label']!r} has missing={missing}, extra={extra}"
            )
        label = (
            f"[{_escape(row['label'])}]"
            f"({_relative_link(row['page'], containing_page)})"
        )
        cells = [_cell(row["cells"][group_id], states, evidence) for group_id in group_ids]
        lines.append("| " + " | ".join([label, *cells]) + " |")
    return _header() + "\n".join(lines) + "\n"


def render_platform(
    platform_id: str, section: dict[str, Any], data: dict[str, Any]
) -> str:
    states = data["states"]
    evidence = data["evidence"]
    variants = section["variants"]
    lines = [
        f"### {section['title']}",
        "",
        "| Capability | " + " | ".join(_escape(item) for item in variants) + " |",
        "|" + "---|" * (len(variants) + 1),
    ]
    for row in section["rows"]:
        label, *cells = row
        if len(cells) != len(variants):
            raise ValueError(
                f"{platform_id} row {label!r} has {len(cells)} cells for "
                f"{len(variants)} variants"
            )
        lines.append(
            "| "
            + " | ".join(
                [_escape(label), *[_cell(cell, states, evidence) for cell in cells]]
            )
            + " |"
        )
    return _header() + "\n".join(lines) + "\n"


def render_application_capabilities(data: dict[str, Any]) -> str:
    matrix = data["application_capabilities"]
    columns = matrix["columns"]
    lines = [
        "| Library capability | " + " | ".join(_escape(item) for item in columns) + " |",
        "|" + "---|" * (len(columns) + 1),
    ]
    for row in matrix["rows"]:
        if len(row) != len(columns) + 1:
            raise ValueError(
                f"application row {row[0]!r} has {len(row) - 1} cells for "
                f"{len(columns)} columns"
            )
        lines.append("| " + " | ".join(_escape(item) for item in row) + " |")
    return _header() + "\n".join(lines) + "\n"


def validate_downloads(data: dict[str, Any]) -> None:
    required = {
        "product",
        "platform",
        "variant",
        "state",
        "artifact",
        "action",
        "url",
        "note",
    }
    seen: set[tuple[str, str, str]] = set()
    for index, entry in enumerate(data["downloads"]):
        missing = required - set(entry)
        extra = set(entry) - required
        if missing or extra:
            raise ValueError(
                f"download entry {index} has missing={missing}, extra={extra}"
            )
        if entry["state"] not in data["states"]:
            raise ValueError(
                f"download entry {index} has unknown state {entry['state']!r}"
            )
        key = (entry["product"], entry["platform"], entry["variant"])
        if key in seen:
            raise ValueError(f"duplicate download selector path: {key!r}")
        seen.add(key)
        if not all(isinstance(entry[field], str) and entry[field] for field in required):
            raise ValueError(f"download entry {index} contains an empty value")


def validate_links(data: dict[str, Any], root: Path) -> None:
    pages = [
        *(group["page"] for group in data["platform_groups"]),
        *(row["page"] for row in data["overview"]),
        *(row["page"] for row in data["feature_overview"]),
    ]
    for page in pages:
        if not (root / "docs" / page).is_file():
            missing = Path("docs") / page
            raise ValueError(f"catalogue page does not exist: {missing.as_posix()}")

    for entry in data["downloads"]:
        url = entry["url"]
        if url.startswith(("https://", "http://")):
            continue
        route = url.strip("/")
        candidates = [root / "docs" / f"{route}.md", root / "docs" / route / "index.md"]
        if not any(candidate.is_file() for candidate in candidates):
            raise ValueError(f"download action does not resolve to a docs page: {url}")


def outputs(data: dict[str, Any]) -> dict[Path, str]:
    validate_downloads(data)
    rendered = {
        GENERATED / "platform-feature-overview.md": render_overview(
            data, "feature_overview", "Feature"
        ),
        GENERATED / "platform-product-overview.md": render_overview(
            data, "overview", "Product or surface"
        ),
        GENERATED / "application-capabilities.md": render_application_capabilities(data),
    }
    for platform_id, section in data["platform_details"].items():
        rendered[GENERATED / f"platform-{platform_id}.md"] = render_platform(
            platform_id, section, data
        )
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument(
        "--check", action="store_true", help="fail when committed output is stale"
    )
    args = parser.parse_args()
    root = args.root.resolve()

    try:
        data = _load(root / CATALOGUE)
        validate_links(data, root)
        rendered = outputs(data)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"::error file={CATALOGUE.as_posix()}::{error}")
        return 1

    stale: list[Path] = []
    for relative, content in rendered.items():
        destination = root / relative
        if args.check:
            if not destination.is_file() or destination.read_text(encoding="utf-8") != content:
                stale.append(relative)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {relative.as_posix()}")

    if args.check:
        generated_dir = root / GENERATED
        expected = set(rendered)
        for existing in generated_dir.glob("*.md"):
            relative = existing.relative_to(root)
            if relative not in expected:
                stale.append(relative)

    if stale:
        for relative in stale:
            print(
                f"::error file={relative.as_posix()}::generated support matrix is stale; "
                "run python tools/checks/generate_support_matrices.py"
            )
        return 1
    if args.check:
        print(f"support matrices: {len(rendered)} generated file(s) current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
