"""Python bindings for ac3forge - a clean-room AC-3/E-AC-3 encoder and decoder in C++23,
including the Atmos-in-DD+ object layer (OAMD + JOC).

Everything here is a thin wrapper over the compiled ``_ac3forge`` extension - see
docs/library/python-api.md in the ac3forge repository for the full surface and worked examples.
"""

from ._ac3forge import (
    BLOCKS_PER_FRAME,
    SAMPLES_PER_FRAME,
    TRANSFORM_DELAY_SAMPLES,
    Ac3DecodeError,
    Ac3EncodeError,
    Ac3Error,
    Ac3ScanError,
    AccessUnitTiming,
    Acmod,
    AtmosConfig,
    AtmosEncoder,
    CentreMixLevel,
    DecodedAccessUnit,
    DecodedFrame,
    DecodedProgram,
    DecodedSubstream,
    DecodeError,
    DecoderConfig,
    DynamicObject,
    Eac3Decoder,
    EncoderConfig,
    FrameDecoder,
    FrameEncoder,
    FrameError,
    FrameHeader,
    HeavyConfig,
    LatencyBudget,
    ObjectPlacement,
    Position,
    Profile,
    ProfileId,
    Program,
    SampleRate,
    ScanError,
    ScannedProgramme,
    ScannedStream,
    StreamKind,
    StreamType,
    SubstreamService,
    SurroundMixLevel,
    access_unit_at_sample,
    access_unit_at_seconds,
    access_unit_timing,
    describe,
    eac3,
    fullbw_channel_count,
    profile_for,
    profile_name,
    read_frame_header,
    sample_rate_hz,
    scan,
    split_access_units,
    split_frames,
    stream_bsid,
    stream_duration_samples,
    stream_duration_seconds,
    uniform_access_unit_samples,
)

try:
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("ac3forge")
except PackageNotFoundError:  # pragma: no cover - an editable/unbuilt checkout
    __version__ = "0.0.0"

__all__ = [
    "BLOCKS_PER_FRAME",
    "SAMPLES_PER_FRAME",
    "TRANSFORM_DELAY_SAMPLES",
    "Ac3DecodeError",
    "Ac3EncodeError",
    "Ac3Error",
    "Ac3ScanError",
    "AccessUnitTiming",
    "Acmod",
    "AtmosConfig",
    "AtmosEncoder",
    "CentreMixLevel",
    "DecodeError",
    "DecodedAccessUnit",
    "DecodedFrame",
    "DecodedProgram",
    "DecodedSubstream",
    "DecoderConfig",
    "DynamicObject",
    "Eac3Decoder",
    "EncoderConfig",
    "FrameDecoder",
    "FrameEncoder",
    "FrameError",
    "FrameHeader",
    "HeavyConfig",
    "LatencyBudget",
    "ObjectPlacement",
    "Position",
    "Profile",
    "ProfileId",
    "Program",
    "SampleRate",
    "ScanError",
    "ScannedProgramme",
    "ScannedStream",
    "StreamKind",
    "StreamType",
    "SubstreamService",
    "SurroundMixLevel",
    "__version__",
    "access_unit_at_sample",
    "access_unit_at_seconds",
    "access_unit_timing",
    "describe",
    "eac3",
    "fullbw_channel_count",
    "profile_for",
    "profile_name",
    "read_frame_header",
    "sample_rate_hz",
    "scan",
    "split_access_units",
    "split_frames",
    "stream_bsid",
    "stream_duration_samples",
    "stream_duration_seconds",
    "uniform_access_unit_samples",
]
